[package]
name = "bake-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bake-tui-view.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[target.'cfg(unix)'.dependencies]
signal-hook = { workspace = true, features = ["iterator"] }
