#!/bin/sh
set -eu

base_url=${BAKE_RELEASE_BASE_URL:-https://bake.justar.dev}
install_root=${BAKE_INSTALL_ROOT:-"$HOME/.local/share/bake"}
bin_dir=${BAKE_BIN_DIR:-"$HOME/.local/bin"}

command -v curl >/dev/null 2>&1 || { echo 'Bake install needs curl.' >&2; exit 1; }
command -v tar >/dev/null 2>&1 || { echo 'Bake install needs tar.' >&2; exit 1; }
command -v node >/dev/null 2>&1 || { echo 'Bake install needs Node.js 24 or newer.' >&2; exit 1; }
node -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 24 ? 0 : 1)' || {
  echo 'Bake install needs Node.js 24 or newer.' >&2
  exit 1
}

case "$(uname -s)-$(uname -m)" in
  Darwin-arm64) target=darwin-arm64 ;;
  Darwin-x86_64) target=darwin-x64 ;;
  Linux-aarch64|Linux-arm64) target=linux-arm64 ;;
  Linux-x86_64) target=linux-x64 ;;
  *) echo 'This platform has no Bake release archive.' >&2; exit 1 ;;
esac

temporary=$(mktemp -d "${TMPDIR:-/tmp}/bake-install.XXXXXX")
animation_pid=
stop_animation() {
  if [ -n "$animation_pid" ]; then
    printf '%s\n' "$1" > "$temporary/progress"
    wait "$animation_pid" 2>/dev/null || :
    animation_pid=
  fi
}
cleanup() {
  stop_animation stop
  if [ -f "$temporary/errors" ]; then cat "$temporary/errors" >&2; fi
  rm -rf "$temporary"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM
if [ -t 2 ] && [ "${TERM:-}" != dumb ] && [ -z "${CI:-}" ] && [ "${BAKE_NO_ANIMATION:-}" != 1 ]; then
  cat > "$temporary/bakery.cjs" <<'BAKERY'
// Generated by bun scripts/release/embed-animation.ts.
// # BEGIN BAKERY
var I=require("node:fs");function h(e,r,_){let a=e.isTTY===!0&&r.TERM!=="dumb"&&!r.CI&&r.BAKE_NO_ANIMATION!=="1",s=r.NO_COLOR===void 0,l=_,f=0,o=!1,d=!1,u=["[##  _____  ##]","[##  (___)  ##]","[## (~~~~~) ##]","[## (~~~~~) ##]"],g=[". . "," : .",". : "," . :"],m=()=>(e.columns!==void 0&&e.columns>0?e.columns:80)-1,p=()=>{let t=Math.floor(f++/3)%u.length,i=`  ${u[t]} ${g[f%g.length]} ${l}`.slice(0,m());e.write(`\r\x1B[2K${s?"\x1B[38;5;215m":""}${i}${s?"\x1B[0m":""}`),d=!0};if(a)p();let b=a?setInterval(p,180):void 0;return b?.unref(),{stage(t){if(!o)l=t},finish(t=!1){if(o)return;if(o=!0,clearInterval(b),!d)return;if(e.write("\r\x1B[2K"),t){let i="  (~~~~~)  Freshly baked.".slice(0,m());e.write(`${s?"\x1B[38;5;215m":""}${i}${s?"\x1B[0m":""}
`)}}}}var x=process.argv[2];if(!x)throw Error("Missing installer progress file");var v=Number(process.argv[3]),n=h(process.stderr,process.env,"Warming the oven..."),c=setInterval(()=>{try{process.kill(v,0);let e=I.readFileSync(x,"utf8").trim();if(e==="done"||e==="stop")clearInterval(c),n.finish(e==="done");else if(e)n.stage(e)}catch{clearInterval(c),n.finish()}},100);for(let e of["SIGINT","SIGTERM"])process.once(e,()=>{clearInterval(c),n.finish()});
// # END BAKERY
BAKERY
  printf '%s\n' 'Checking the recipe...' > "$temporary/progress"
  node "$temporary/bakery.cjs" "$temporary/progress" "$$" &
  animation_pid=$!
fi
install_bake() {
curl -fsSL "$base_url/latest.json" -o "$temporary/latest.json"
curl -fsSL "$base_url/latest.json.sig" -o "$temporary/latest.json.sig"
node - "$temporary/latest.json" "$target" "$temporary/latest.json.sig" > "$temporary/selected" <<'NODE'
const fs = require('node:fs')
const crypto = require('node:crypto')
// The release signing key; BAKE_RELEASE_PUBLIC_KEY adds one for a local check.
const keys = ['MCowBQYDK2VwAyEAG1Z33Mis04XnFsekLrnPDBwSgn26uNeLz3XtGal+xC4=', process.env.BAKE_RELEASE_PUBLIC_KEY]
  .filter(key => typeof key === 'string' && key.trim() !== '')
const bytes = fs.readFileSync(process.argv[2])
const signature = Buffer.from(fs.readFileSync(process.argv[4], 'utf8').trim(), 'base64')
const signed = signature.length === 64 && keys.some(key => {
  try { return crypto.verify(null, bytes, crypto.createPublicKey({ key: Buffer.from(key.trim(), 'base64'), format: 'der', type: 'spki' }), signature) } catch { return false }
})
if (!signed) {
  console.error('The Bake release manifest signature did not verify.')
  process.exit(1)
}
const manifest = JSON.parse(bytes.toString('utf8'))
const target = process.argv[3]
const artifact = manifest.artifacts?.[target]
if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(manifest.version)
  || artifact?.file !== `bake-v${manifest.version}-${target}.tar.gz`
  || !/^[a-f0-9]{64}$/.test(artifact.sha256)) {
  console.error(`No valid Bake archive for ${target}`)
  process.exit(1)
}
console.log(manifest.version)
console.log(artifact.file)
console.log(artifact.sha256)
NODE
version=$(sed -n '1p' "$temporary/selected")
file=$(sed -n '2p' "$temporary/selected")
expected=$(sed -n '3p' "$temporary/selected")
# A GitHub host serves each archive from its own tag; see archiveUrl in the updater.
case $base_url in
  https://github.com/*/*/releases/latest/download) archive_url="${base_url%/latest/download}/download/v$version/$file" ;;
  *) archive_url="$base_url/releases/$version/$file" ;;
esac
printf '%s\n' 'Gathering ingredients...' > "$temporary/progress"
curl -fsSL "$archive_url" -o "$temporary/$file"
printf '%s\n' 'Checking ingredients...' > "$temporary/progress"
if command -v shasum >/dev/null 2>&1; then
  actual=$(shasum -a 256 "$temporary/$file" | cut -d ' ' -f 1)
elif command -v sha256sum >/dev/null 2>&1; then
  actual=$(sha256sum "$temporary/$file" | cut -d ' ' -f 1)
else
  echo 'Bake install needs shasum or sha256sum.' >&2
  exit 1
fi
if [ "$actual" != "$expected" ]; then
  echo 'Bake download checksum did not match the release manifest.' >&2
  exit 1
fi

printf '%s\n' 'Baking your release...' > "$temporary/progress"
mkdir -p "$install_root/versions" "$bin_dir" "$temporary/unpacked"
tar -xzf "$temporary/$file" -C "$temporary/unpacked"
node "$temporary/unpacked/apps/cli/lib/bin.js" --version >/dev/null
digest_prefix=$(printf '%s' "$expected" | cut -c 1-12)
new_version="$install_root/versions/$version-$digest_prefix"
if [ -d "$new_version" ]; then
  node "$new_version/apps/cli/lib/bin.js" --version >/dev/null
else
  mv "$temporary/unpacked" "$new_version"
fi
ln -s "$new_version" "$install_root/.current-$$"
if [ -L "$install_root/current" ]; then
  rm "$install_root/current"
elif [ -e "$install_root/current" ]; then
  echo "$install_root/current exists and is not a Bake-managed link." >&2
  exit 1
fi
mv -f "$install_root/.current-$$" "$install_root/current"
ln -s "$install_root/current/bin/bake" "$bin_dir/.bake-$$"
if [ -L "$bin_dir/bake" ]; then
  rm "$bin_dir/bake"
elif [ -e "$bin_dir/bake" ]; then
  echo "$bin_dir/bake exists and is not a Bake-managed link." >&2
  exit 1
fi
mv -f "$bin_dir/.bake-$$" "$bin_dir/bake"

}
install_bake 2> "$temporary/errors"
stop_animation 'done'

echo "Installed Bake $version at $new_version"
case ":$PATH:" in
  *":$bin_dir:"*) echo 'Run: bake' ;;
  *) echo "Add $bin_dir to PATH, then run: bake" ;;
esac
