$ErrorActionPreference = 'Stop'

$baseUrl = if ($env:BAKE_RELEASE_BASE_URL) { $env:BAKE_RELEASE_BASE_URL.TrimEnd('/') } else { 'https://bake.justar.dev' }
$installRoot = if ($env:BAKE_INSTALL_ROOT) { $env:BAKE_INSTALL_ROOT } else { Join-Path $env:LOCALAPPDATA 'Bake' }
# Written into the launcher, so it must not depend on the directory the installer ran from.
$installRoot = [IO.Path]::GetFullPath($installRoot)
$binDir = if ($env:BAKE_BIN_DIR) { $env:BAKE_BIN_DIR } else { Join-Path $installRoot 'bin' }

if (-not [Environment]::Is64BitOperatingSystem -or $env:PROCESSOR_ARCHITECTURE -ne 'AMD64') {
  throw 'This Windows platform has no Bake release archive.'
}
try { $nodeMajor = [int]((& node -p 'process.versions.node').Trim().Split('.')[0]) }
catch { throw 'Bake install needs Node.js 24 or newer on PATH.' }
if ($nodeMajor -lt 24) { throw 'Bake install needs Node.js 24 or newer on PATH.' }
if (-not (Get-Command tar.exe -ErrorAction SilentlyContinue)) { throw 'Bake install needs Windows tar.exe.' }

$temporary = Join-Path ([IO.Path]::GetTempPath()) ("bake-install-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temporary | Out-Null
$animation = $null
$previousProgressPreference = $ProgressPreference
$ProgressPreference = 'SilentlyContinue'
$progressPath = Join-Path $temporary 'progress'
function Set-BakeStage([string]$Stage) {
  [IO.File]::WriteAllText($progressPath, $Stage, [Text.Encoding]::ASCII)
}
function Stop-BakeAnimation([string]$Stage) {
  if ($null -ne $script:animation) {
    Set-BakeStage $Stage
    $script:animation.WaitForExit()
    $script:animation.Dispose()
    $script:animation = $null
  }
}
try {
  if (-not [Console]::IsErrorRedirected -and $env:TERM -ne 'dumb' -and -not $env:CI -and $env:BAKE_NO_ANIMATION -ne '1') {
    $animationPath = Join-Path $temporary 'bakery.cjs'
    Set-Content -Path $animationPath -Encoding Ascii -Value @'
// Generated by bun scripts/release/embed-animation.ts.
// # BEGIN BAKERY
var R=require("node:fs");var h=["#f5e6c4","#f0d49a","#e8ba68","#dc9c3f","#c97f2a","#ab621f","#8b4a17"];var g=120,y=3,C="\u2584\u2586\u2588\u2588\u2588\u2586\u2584",d=[".",":","=","#"],p=6,O=[[1,2,4,64],[8,16,32,128]],L=Array.from({length:p*2},(e,t)=>Array.from({length:y},(r,n)=>{let o=(t+n*2)%p,a=t+n>>1&1,s=0;for(let[c,i]of[[0,o],[1,o-1]]){if(i<0||i>3)continue;s|=O[a+c&1][3-i]}return String.fromCodePoint(10240+s)}).join("")),P=[".",":","'","`"," "," "],A=Array.from({length:p},(e,t)=>Array.from({length:y},(r,n)=>P[(t+n*2)%p]).join(""));function _(e){let t=Math.min(1,Math.max(0,Number.isFinite(e)?e:0));return h[Math.round(t*(h.length-1))]}function S(e,t,r){let n=Math.floor(Math.max(0,e)/g),o=_(t);if(r==="unicode")return{steam:L[n%L.length],loaf:C,tone:o};let a=d[Math.min(d.length-1,Math.floor(Math.min(1,Math.max(0,t))*d.length))];return{steam:A[n%A.length],loaf:`(${a.repeat(5)})`,tone:o}}function F(e){return{steam:" ".repeat(y),loaf:e==="unicode"?C:`(${d.at(-1).repeat(5)})`,tone:_(1)}}function I(e){let t=[e.LC_ALL,e.LC_CTYPE,e.LANG].find((r)=>r!==void 0&&r!=="")?.toLowerCase();if(t===void 0||!/utf-?8/.test(t))return"ascii";if(e.TERM===void 0||e.TERM===""||e.TERM==="dumb")return"ascii";return/^(zh|ja|ko)/.test(t)?"ascii":"unicode"}function G(e){let t=[0,95,135,175,215,255],r=(s)=>t.reduce((c,i,l)=>Math.abs(i-s)<Math.abs(t[c]-s)?l:c,0),[n,o,a]=[1,3,5].map((s)=>r(Number.parseInt(e.slice(s,s+2),16)));return 16+36*n+6*o+a}function b(e,t,r){let n=`  ${e.steam} ${e.loaf}  `,o=Math.max(0,r.width-n.length),a=[...t].length>o?`${[...t].slice(0,Math.max(0,o-1)).join("")}${o>0?"\u2026":""}`:t;if(n.length>r.width)return"";if(!r.color)return`${n}${a}`;return`  \x1B[2m${e.steam}\x1B[22m \x1B[38;5;${G(e.tone)}m${e.loaf}\x1B[39m  ${a}`}var B=0.8,D=20000;function k(e,t,r){let n=e.isTTY===!0&&t.TERM!=="dumb"&&!t.CI&&t.BAKE_NO_ANIMATION!=="1",o=t.NO_COLOR===void 0,a=I(t),s=Date.now(),c=r,i,l=!1,T=!1,E=()=>(e.columns!==void 0&&e.columns>0?e.columns:80)-1,M=()=>{let f=Date.now()-s,u=i??B*(1-Math.exp(-f/D));e.write(`\r\x1B[2K${b(S(f,u,a),c,{color:o,width:E()})}`),T=!0};if(n)M();let w=n?setInterval(M,g):void 0;return w?.unref(),{stage(f,u){if(l)return;if(c=f,u!==void 0)i=u},finish(f=!1){if(l)return;if(l=!0,clearInterval(w),!T)return;if(e.write("\r\x1B[2K"),f)e.write(`${b(F(a),"Freshly baked.",{color:o,width:E()})}
`)}}}var N=process.argv[2];if(!N)throw Error("Missing installer progress file");var v=Number(process.argv[3]),m=k(process.stderr,process.env,"Warming the oven..."),x=setInterval(()=>{try{process.kill(v,0);let e=R.readFileSync(N,"utf8").trim();if(e==="done"||e==="stop")clearInterval(x),m.finish(e==="done");else if(e)m.stage(e)}catch{clearInterval(x),m.finish()}},100);for(let e of["SIGINT","SIGTERM"])process.once(e,()=>{clearInterval(x),m.finish()});
// # END BAKERY
'@
    Set-BakeStage 'Checking the recipe...'
    $animation = Start-Process -FilePath (Get-Command node).Source -ArgumentList @(('"' + $animationPath + '"'), ('"' + $progressPath + '"'), "$PID") -NoNewWindow -PassThru
  }
  # The signature covers the manifest's exact bytes, so both are saved as
  # served and checked before either is parsed.
  $manifestPath = Join-Path $temporary 'latest.json'
  $signaturePath = Join-Path $temporary 'latest.json.sig'
  Invoke-WebRequest "$baseUrl/latest.json" -UseBasicParsing -OutFile $manifestPath
  Invoke-WebRequest "$baseUrl/latest.json.sig" -UseBasicParsing -OutFile $signaturePath
  $verifier = Join-Path $temporary 'verify.cjs'
  Set-Content -Path $verifier -Encoding Ascii -Value @'
const fs = require('node:fs')
const crypto = require('node:crypto')
// The release signing key; BAKE_RELEASE_PUBLIC_KEY adds one for a local check.
const keys = ['MCowBQYDK2VwAyEAG1Z33Mis04XnFsekLrnPDBwSgn26uNeLz3XtGal+xC4=', process.env.BAKE_RELEASE_PUBLIC_KEY]
  .filter(key => typeof key === 'string' && key.trim() !== '')
const bytes = fs.readFileSync(process.argv[2])
const signature = Buffer.from(fs.readFileSync(process.argv[3], 'utf8').trim(), 'base64')
const signed = signature.length === 64 && keys.some(key => {
  try { return crypto.verify(null, bytes, crypto.createPublicKey({ key: Buffer.from(key.trim(), 'base64'), format: 'der', type: 'spki' }), signature) } catch { return false }
})
process.exit(signed ? 0 : 1)
'@
  & node $verifier $manifestPath $signaturePath
  if ($LASTEXITCODE -ne 0) { throw 'The Bake release manifest signature did not verify.' }
  $manifest = Get-Content -Raw -Path $manifestPath | ConvertFrom-Json
  $version = [string]$manifest.version
  $artifact = $manifest.artifacts.'win32-x64'
  if ($version -notmatch '^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$' -or
      -not $artifact -or
      [string]$artifact.file -ne "bake-v$version-win32-x64.tar.gz" -or
      [string]$artifact.sha256 -notmatch '^[a-f0-9]{64}$') {
    throw 'No valid Bake archive for win32-x64.'
  }
  $archive = Join-Path $temporary $artifact.file
  # A GitHub host serves each archive from its own tag; see archiveUrl in the updater.
  $archiveUrl = if ($baseUrl -match '^(https://github\.com/[^/]+/[^/]+/releases)/latest/download$') {
    "$($Matches[1])/download/v$version/$($artifact.file)"
  } else { "$baseUrl/releases/$version/$($artifact.file)" }
  Set-BakeStage 'Gathering ingredients...'
  Invoke-WebRequest $archiveUrl -UseBasicParsing -OutFile $archive
  Set-BakeStage 'Checking ingredients...'
  $actual = (Get-FileHash -Algorithm SHA256 $archive).Hash.ToLowerInvariant()
  if ($actual -ne $artifact.sha256) { throw 'Bake download checksum did not match the release manifest.' }
  Set-BakeStage 'Baking your release...'
  $unpacked = Join-Path $temporary 'unpacked'
  New-Item -ItemType Directory -Path $unpacked | Out-Null
  & tar.exe -xzf $archive -C $unpacked
  if ($LASTEXITCODE -ne 0) { throw 'Could not extract the Bake archive.' }
  & node (Join-Path $unpacked 'apps\cli\lib\bin.js') --version | Out-Null
  if ($LASTEXITCODE -ne 0) { throw 'The Bake archive did not start.' }

  $versions = Join-Path $installRoot 'versions'
  New-Item -ItemType Directory -Force -Path $versions, $binDir | Out-Null
  $digestPrefix = ([string]$artifact.sha256).Substring(0, 12)
  $versionPath = Join-Path $versions "$version-$digestPrefix"
  if (Test-Path $versionPath) {
    & node (Join-Path $versionPath 'apps\cli\lib\bin.js') --version | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'The existing Bake installation did not start.' }
  } else {
    Move-Item $unpacked $versionPath
  }
  # The pointer names the current release; `bake update` moves it the same
  # way, by replacing the whole file.
  $pointer = Join-Path $installRoot 'current.txt'
  $pointerNext = "$pointer.$PID.tmp"
  [IO.File]::WriteAllText($pointerNext, "$version-$digestPrefix`r`n", [Text.Encoding]::ASCII)
  Move-Item -Force -LiteralPath $pointerNext -Destination $pointer
  # The launcher reads that pointer, so no update ever rewrites it; the
  # release ships its text, the same text the updater writes.
  $template = Join-Path $versionPath 'bin\bake-launcher.cmd.template'
  if (-not (Test-Path $template)) { throw 'The Bake archive has no launcher template.' }
  $commandText = [IO.File]::ReadAllText($template).Replace('@@BAKE_RELEASE_ROOT@@', $installRoot.Replace('%', '%%'))
  $cmd = Join-Path $binDir 'bake.cmd'
  [IO.File]::WriteAllText($cmd, $commandText, [Text.Encoding]::ASCII)
  if ($env:BAKE_SKIP_PATH_UPDATE -ne '1') {
    $pathParts = [Environment]::GetEnvironmentVariable('Path', 'User') -split ';'
    if ($pathParts -notcontains $binDir) {
      $existing = [Environment]::GetEnvironmentVariable('Path', 'User')
      [Environment]::SetEnvironmentVariable('Path', (($existing.TrimEnd(';') + ';' + $binDir).TrimStart(';')), 'User')
    }
  }
  $env:Path += ";$binDir"
  Stop-BakeAnimation done
  Write-Output "Installed Bake $version at $versionPath. Run: bake"
} finally {
  Stop-BakeAnimation stop
  $ProgressPreference = $previousProgressPreference
  Remove-Item -Recurse -Force $temporary -ErrorAction SilentlyContinue
}
