$ErrorActionPreference = 'Stop'

$baseUrl = if ($env:BAKE_RELEASE_BASE_URL) { $env:BAKE_RELEASE_BASE_URL.TrimEnd('/') } else { 'https://bake.justar.dev' }
$installRoot = if ($env:BAKE_INSTALL_ROOT) { $env:BAKE_INSTALL_ROOT } else { Join-Path $env:LOCALAPPDATA 'Bake' }
# Written into the launcher, so it must not depend on the directory the installer ran from.
$installRoot = [IO.Path]::GetFullPath($installRoot)
$binDir = if ($env:BAKE_BIN_DIR) { $env:BAKE_BIN_DIR } else { Join-Path $installRoot 'bin' }

if (-not [Environment]::Is64BitOperatingSystem -or $env:PROCESSOR_ARCHITECTURE -ne 'AMD64') {
  throw 'This Windows platform has no Bake release archive.'
}
try { $nodeMajor = [int]((& node -p 'process.versions.node').Trim().Split('.')[0]) }
catch { throw 'Bake install needs Node.js 24 or newer on PATH.' }
if ($nodeMajor -lt 24) { throw 'Bake install needs Node.js 24 or newer on PATH.' }
if (-not (Get-Command tar.exe -ErrorAction SilentlyContinue)) { throw 'Bake install needs Windows tar.exe.' }

$temporary = Join-Path ([IO.Path]::GetTempPath()) ("bake-install-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temporary | Out-Null
$animation = $null
$previousProgressPreference = $ProgressPreference
$ProgressPreference = 'SilentlyContinue'
$progressPath = Join-Path $temporary 'progress'
function Set-BakeStage([string]$Stage) {
  [IO.File]::WriteAllText($progressPath, $Stage, [Text.Encoding]::ASCII)
}
function Stop-BakeAnimation([string]$Stage) {
  if ($null -ne $script:animation) {
    Set-BakeStage $Stage
    $script:animation.WaitForExit()
    $script:animation.Dispose()
    $script:animation = $null
  }
}
try {
  if (-not [Console]::IsErrorRedirected -and $env:TERM -ne 'dumb' -and -not $env:CI -and $env:BAKE_NO_ANIMATION -ne '1') {
    $animationPath = Join-Path $temporary 'bakery.cjs'
    Set-Content -Path $animationPath -Encoding Ascii -Value @'
// Generated by bun scripts/release/embed-animation.ts.
// # BEGIN BAKERY
var I=require("node:fs");function h(e,r,_){let a=e.isTTY===!0&&r.TERM!=="dumb"&&!r.CI&&r.BAKE_NO_ANIMATION!=="1",s=r.NO_COLOR===void 0,l=_,f=0,o=!1,d=!1,u=["[##  _____  ##]","[##  (___)  ##]","[## (~~~~~) ##]","[## (~~~~~) ##]"],g=[". . "," : .",". : "," . :"],m=()=>(e.columns!==void 0&&e.columns>0?e.columns:80)-1,p=()=>{let t=Math.floor(f++/3)%u.length,i=`  ${u[t]} ${g[f%g.length]} ${l}`.slice(0,m());e.write(`\r\x1B[2K${s?"\x1B[38;5;215m":""}${i}${s?"\x1B[0m":""}`),d=!0};if(a)p();let b=a?setInterval(p,180):void 0;return b?.unref(),{stage(t){if(!o)l=t},finish(t=!1){if(o)return;if(o=!0,clearInterval(b),!d)return;if(e.write("\r\x1B[2K"),t){let i="  (~~~~~)  Freshly baked.".slice(0,m());e.write(`${s?"\x1B[38;5;215m":""}${i}${s?"\x1B[0m":""}
`)}}}}var x=process.argv[2];if(!x)throw Error("Missing installer progress file");var v=Number(process.argv[3]),n=h(process.stderr,process.env,"Warming the oven..."),c=setInterval(()=>{try{process.kill(v,0);let e=I.readFileSync(x,"utf8").trim();if(e==="done"||e==="stop")clearInterval(c),n.finish(e==="done");else if(e)n.stage(e)}catch{clearInterval(c),n.finish()}},100);for(let e of["SIGINT","SIGTERM"])process.once(e,()=>{clearInterval(c),n.finish()});
// # END BAKERY
'@
    Set-BakeStage 'Checking the recipe...'
    $animation = Start-Process -FilePath (Get-Command node).Source -ArgumentList @(('"' + $animationPath + '"'), ('"' + $progressPath + '"'), "$PID") -NoNewWindow -PassThru
  }
  # The signature covers the manifest's exact bytes, so both are saved as
  # served and checked before either is parsed.
  $manifestPath = Join-Path $temporary 'latest.json'
  $signaturePath = Join-Path $temporary 'latest.json.sig'
  Invoke-WebRequest "$baseUrl/latest.json" -UseBasicParsing -OutFile $manifestPath
  Invoke-WebRequest "$baseUrl/latest.json.sig" -UseBasicParsing -OutFile $signaturePath
  $verifier = Join-Path $temporary 'verify.cjs'
  Set-Content -Path $verifier -Encoding Ascii -Value @'
const fs = require('node:fs')
const crypto = require('node:crypto')
// The release signing key; BAKE_RELEASE_PUBLIC_KEY adds one for a local check.
const keys = ['MCowBQYDK2VwAyEAG1Z33Mis04XnFsekLrnPDBwSgn26uNeLz3XtGal+xC4=', process.env.BAKE_RELEASE_PUBLIC_KEY]
  .filter(key => typeof key === 'string' && key.trim() !== '')
const bytes = fs.readFileSync(process.argv[2])
const signature = Buffer.from(fs.readFileSync(process.argv[3], 'utf8').trim(), 'base64')
const signed = signature.length === 64 && keys.some(key => {
  try { return crypto.verify(null, bytes, crypto.createPublicKey({ key: Buffer.from(key.trim(), 'base64'), format: 'der', type: 'spki' }), signature) } catch { return false }
})
process.exit(signed ? 0 : 1)
'@
  & node $verifier $manifestPath $signaturePath
  if ($LASTEXITCODE -ne 0) { throw 'The Bake release manifest signature did not verify.' }
  $manifest = Get-Content -Raw -Path $manifestPath | ConvertFrom-Json
  $version = [string]$manifest.version
  $artifact = $manifest.artifacts.'win32-x64'
  if ($version -notmatch '^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$' -or
      -not $artifact -or
      [string]$artifact.file -ne "bake-v$version-win32-x64.tar.gz" -or
      [string]$artifact.sha256 -notmatch '^[a-f0-9]{64}$') {
    throw 'No valid Bake archive for win32-x64.'
  }
  $archive = Join-Path $temporary $artifact.file
  # A GitHub host serves each archive from its own tag; see archiveUrl in the updater.
  $archiveUrl = if ($baseUrl -match '^(https://github\.com/[^/]+/[^/]+/releases)/latest/download$') {
    "$($Matches[1])/download/v$version/$($artifact.file)"
  } else { "$baseUrl/releases/$version/$($artifact.file)" }
  Set-BakeStage 'Gathering ingredients...'
  Invoke-WebRequest $archiveUrl -UseBasicParsing -OutFile $archive
  Set-BakeStage 'Checking ingredients...'
  $actual = (Get-FileHash -Algorithm SHA256 $archive).Hash.ToLowerInvariant()
  if ($actual -ne $artifact.sha256) { throw 'Bake download checksum did not match the release manifest.' }
  Set-BakeStage 'Baking your release...'
  $unpacked = Join-Path $temporary 'unpacked'
  New-Item -ItemType Directory -Path $unpacked | Out-Null
  & tar.exe -xzf $archive -C $unpacked
  if ($LASTEXITCODE -ne 0) { throw 'Could not extract the Bake archive.' }
  & node (Join-Path $unpacked 'apps\cli\lib\bin.js') --version | Out-Null
  if ($LASTEXITCODE -ne 0) { throw 'The Bake archive did not start.' }

  $versions = Join-Path $installRoot 'versions'
  New-Item -ItemType Directory -Force -Path $versions, $binDir | Out-Null
  $digestPrefix = ([string]$artifact.sha256).Substring(0, 12)
  $versionPath = Join-Path $versions "$version-$digestPrefix"
  if (Test-Path $versionPath) {
    & node (Join-Path $versionPath 'apps\cli\lib\bin.js') --version | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'The existing Bake installation did not start.' }
  } else {
    Move-Item $unpacked $versionPath
  }
  # The pointer names the current release; `bake update` moves it the same
  # way, by replacing the whole file.
  $pointer = Join-Path $installRoot 'current.txt'
  $pointerNext = "$pointer.$PID.tmp"
  [IO.File]::WriteAllText($pointerNext, "$version-$digestPrefix`r`n", [Text.Encoding]::ASCII)
  Move-Item -Force -LiteralPath $pointerNext -Destination $pointer
  # The launcher reads that pointer, so no update ever rewrites it; the
  # release ships its text, the same text the updater writes.
  $template = Join-Path $versionPath 'bin\bake-launcher.cmd.template'
  if (-not (Test-Path $template)) { throw 'The Bake archive has no launcher template.' }
  $commandText = [IO.File]::ReadAllText($template).Replace('@@BAKE_RELEASE_ROOT@@', $installRoot.Replace('%', '%%'))
  $cmd = Join-Path $binDir 'bake.cmd'
  [IO.File]::WriteAllText($cmd, $commandText, [Text.Encoding]::ASCII)
  if ($env:BAKE_SKIP_PATH_UPDATE -ne '1') {
    $pathParts = [Environment]::GetEnvironmentVariable('Path', 'User') -split ';'
    if ($pathParts -notcontains $binDir) {
      $existing = [Environment]::GetEnvironmentVariable('Path', 'User')
      [Environment]::SetEnvironmentVariable('Path', (($existing.TrimEnd(';') + ';' + $binDir).TrimStart(';')), 'User')
    }
  }
  $env:Path += ";$binDir"
  Stop-BakeAnimation done
  Write-Output "Installed Bake $version at $versionPath. Run: bake"
} finally {
  Stop-BakeAnimation stop
  $ProgressPreference = $previousProgressPreference
  Remove-Item -Recurse -Force $temporary -ErrorAction SilentlyContinue
}
