#!/bin/sh
set -eu

base_url=${BAKE_RELEASE_BASE_URL:-https://bake.justar.dev}
install_root=${BAKE_INSTALL_ROOT:-"$HOME/.local/share/bake"}
bin_dir=${BAKE_BIN_DIR:-"$HOME/.local/bin"}

command -v curl >/dev/null 2>&1 || { echo 'Bake install needs curl.' >&2; exit 1; }
command -v tar >/dev/null 2>&1 || { echo 'Bake install needs tar.' >&2; exit 1; }
command -v node >/dev/null 2>&1 || { echo 'Bake install needs Node.js 24 or newer.' >&2; exit 1; }
node -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 24 ? 0 : 1)' || {
  echo 'Bake install needs Node.js 24 or newer.' >&2
  exit 1
}

case "$(uname -s)-$(uname -m)" in
  Darwin-arm64) target=darwin-arm64 ;;
  Darwin-x86_64) target=darwin-x64 ;;
  Linux-aarch64|Linux-arm64) target=linux-arm64 ;;
  Linux-x86_64) target=linux-x64 ;;
  *) echo 'This platform has no Bake release archive.' >&2; exit 1 ;;
esac

temporary=$(mktemp -d "${TMPDIR:-/tmp}/bake-install.XXXXXX")
animation_pid=
# Append one progress event, its fields separated by tabs; see installer-animation.ts.
report() {
  [ -n "$animation_pid" ] || return 0
  (IFS=$(printf '\t'); printf '%s\n' "$*") >> "$temporary/progress"
}
stop_animation() {
  if [ -n "$animation_pid" ]; then
    report "$@"
    wait "$animation_pid" 2>/dev/null || :
    animation_pid=
  fi
}
cleanup() {
  stop_animation stop
  if [ -f "$temporary/errors" ]; then cat "$temporary/errors" >&2; fi
  rm -rf "$temporary"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM
if [ -t 2 ] && [ "${TERM:-}" != dumb ] && [ -z "${CI:-}" ] && [ "${BAKE_NO_ANIMATION:-}" != 1 ]; then
  cat > "$temporary/animation.cjs" <<'ANIMATION'
// Generated by bun scripts/release/embed-animation.ts.
// # BEGIN ANIMATION
var D=require("node:fs"),oe=require("node:path");var E={reference:"#60a5fa",code:"#c4b5fd",running:"#f97316",compacting:"#3b82f6",done:"#22c55e",failed:"#ef4444",asking:"#0ea5e9",waiting:"#eab308",output:"#b4b8bf"},p={from:E.running,to:"#fbbf24",glint:"#fff7ed",track:"#44403c"};var W=80,S=2,K=2,le=10,ce=32,L=1600,k=4,j=1800,N=[[0,0],[1,0],[2,0],[3,0],[3,1],[3,2],[3,3],[2,3],[1,3],[0,3],[0,2],[0,1]],de=4,ue=[[1,2,4,64],[8,16,32,128]],H=["-","\\","|","/"],P={unicode:{fill:"\u2501",edge:"\u2578",track:"\u2500",done:"\u2713",failed:"\u2717",separator:" \u00b7 ",ellipsis:"\u2026"},ascii:{fill:"=",edge:">",track:"-",done:"+",failed:"x",separator:" - ",ellipsis:"..."}},F=(e)=>Math.min(1,Math.max(0,Number.isFinite(e)?e:0));function _(e,t,s){let n=F(s),r=(l,i)=>Number.parseInt(l.slice(1+i*2,3+i*2),16);return`#${[0,1,2].map((l)=>Math.round(r(e,l)+(r(t,l)-r(e,l))*n).toString(16).padStart(2,"0")).join("")}`}function fe(e,t){let s=Math.floor(Math.max(0,e)/W);if(t==="ascii")return[{text:`${H[s%H.length]} `,color:p.from,bold:!0}];let n=[0,0],r=s%N.length;for(let i=0;i<de;i++){let[o,a]=N[(r-i+N.length)%N.length];n[o>>1]|=ue[o&1][a]}let l=N[r][0]>>1;return n.map((i,o)=>({text:String.fromCodePoint(10240+i),color:o===l?p.to:p.from,bold:!0}))}function pe(e,t,s,n){let r=Math.max(0,Math.floor(s)),{fill:l,edge:i,track:o}=P[n],a=[],c=Math.max(0,e),f=(u)=>_(p.from,p.to,r<=1?0:u/(r-1));if(t!==void 0){let u=F(t)*r,m=Math.floor(u),y=m<r&&u-m>=0.5,ie=c%L/L*(m+k*2)-k;for(let x=0;x<m;x++){let ae=Math.max(0,1-Math.abs(x-ie)/k)**2*0.75;a.push({text:l,color:_(f(x),p.glint,ae)})}if(y){let x=(1-Math.cos(2*Math.PI*(c%L)/L))/2;a.push({text:i,color:_(f(m),p.glint,0.2+0.5*x)})}for(let x=m+(y?1:0);x<r;x++)a.push({text:o,dim:!0});return v(a)}let h=c%j/j,g=h<0.5,R=(1-Math.cos(Math.PI*(g?h*2:(1-h)*2)))/2*Math.max(0,r-1),d=Math.max(3,Math.round(r/4));for(let u=0;u<r;u++){let m=g?R-u:u-R,y=m<-0.5||m>d?0:m<=0?1:(1-m/d)**1.5;if(y<0.15){a.push({text:o,dim:!0});continue}a.push({text:n==="ascii"&&y<0.35?o:l,color:y>0.7?_(p.to,p.glint,(y-0.7)/0.3*0.6):_(p.track,p.from,y/0.7)})}return v(a)}function z(e,t){let{time:s,width:n,glyphs:r}=t,l=[...fe(s,r),{text:" "}],i=M(e.label,r),o=Math.max(w(i),t.labelWidth??0),a=[...e.fraction===void 0?[]:[{text:`${Math.floor(F(e.fraction)*100)}%`.padStart(4)}],...e.detail===void 0||e.detail===""?[]:[{text:M(e.detail,r),dim:!0}],...t.elapsed===void 0?[]:[{text:G(t.elapsed),dim:!0}]];for(let c=a.length;c>=0;c--){let f=a.slice(0,c),h=K+1+o+S+f.reduce((g,O)=>g+S+w(O.text),0);if(n-h<le)continue;return[...l,{text:i.padEnd(o)},{text:" ".repeat(S)},...pe(s,e.fraction,Math.min(ce,n-h),r),...f.flatMap((g)=>[{text:" ".repeat(S)},g])]}return I([...l,{text:i}],n,r)}function Y(e,t,s,n){let{glyphs:r}=n,l=M(t,r),i=e==="done"?{text:P[r].done,color:E.done,bold:!0}:{text:P[r].failed,color:E.failed,bold:!0},o=s.filter((a)=>a!=="").map((a)=>M(a,r));return I([i,{text:" ".repeat(K)},{text:o.length===0?l:l.padEnd(Math.max(w(l),n.labelWidth??0)),...e==="failed"?{color:E.failed}:{}},...o.length===0?[]:[{text:" ".repeat(S)},{text:o.join(P[r].separator),dim:!0}]],n.width,r)}function U(e,t,s){let n=e.filter((r)=>r!=="").map((r)=>M(r,s)).join(P[s].separator);return I([{text:"BAKE",color:E.running,bold:!0},...n===""?[]:[{text:" ".repeat(S)},{text:n,dim:!0}]],t,s)}function q(e,t,s,n){return I([{text:M(e,n),bold:!0},...t===void 0?[]:[{text:` in ${G(t)}`,dim:!0}]],s,n)}function J(e,t,s){let n=M(e,s),r=/^(.*\brun: )(\S.*)$/iu.exec(n);return I(r===null?[{text:n}]:[{text:r[1],dim:!0},{text:r[2],color:E.running,bold:!0}],t,s)}function G(e){let t=Math.max(0,e)/1000;if(t<0.1)return"<0.1s";if(t<10)return`${t.toFixed(1)}s`;if(t<60)return`${Math.floor(t)}s`;return`${Math.floor(t/60)}m ${String(Math.floor(t%60)).padStart(2,"0")}s`}function Q(e){let t=[e.LC_ALL,e.LC_CTYPE,e.LANG].find((s)=>s!==void 0&&s!=="")?.toLowerCase();if(t!==void 0&&/^(zh|ja|ko)/.test(t))return"ascii";if(e.WT_SESSION!==void 0&&e.WT_SESSION!=="")return"unicode";if(t===void 0||!/utf-?8/.test(t))return"ascii";if(e.TERM===void 0||e.TERM===""||e.TERM==="dumb")return"ascii";return"unicode"}function V(e){if(e.NO_COLOR!==void 0)return"none";let t=e.COLORTERM?.toLowerCase();if(t==="truecolor"||t==="24bit"||e.WT_SESSION!==void 0&&e.WT_SESSION!=="")return"truecolor";return"ansi256"}function me(e){let t=[0,95,135,175,215,255],s=(i)=>t.reduce((o,a,c)=>Math.abs(a-i)<Math.abs(t[o]-i)?c:o,0),[n,r,l]=[1,3,5].map((i)=>s(Number.parseInt(e.slice(i,i+2),16)));return 16+36*n+6*r+l}function Z(e,t){if(t==="none")return e.map((n)=>n.text).join("");let s=[];for(let n of e){let r=[...n.bold===!0?["1"]:[],...n.dim===!0?["2"]:[]];if(n.color!==void 0){let o=(a)=>Number.parseInt(n.color.slice(1+a*2,3+a*2),16);r.push(t==="truecolor"?`38;2;${o(0)};${o(1)};${o(2)}`:`38;5;${me(n.color)}`)}let l=r.join(";"),i=s.at(-1);if(i!==void 0&&i.code===l)i.text+=n.text;else s.push({code:l,text:n.text})}return s.map((n)=>n.code===""?n.text:`\x1B[${n.code}m${n.text}\x1B[0m`).join("")}function v(e){let t=[];for(let s of e){let n=t.at(-1);if(n!==void 0&&n.color===s.color&&n.dim===s.dim&&n.bold===s.bold)t[t.length-1]={...n,text:n.text+s.text};else t.push(s)}return t}function w(e){return[...e].length}function M(e,t){return t==="unicode"?e:e.replace(/\u2192/gu,"->").replace(/\u00b7/gu,"-").replace(/\u2026/gu,"...")}function I(e,t,s){let n=Math.max(0,Math.floor(t));if(e.reduce((a,c)=>a+w(c.text),0)<=n)return e;let r=P[s].ellipsis,l=Math.max(0,n-w(r)),i=[],o=0;for(let a of e){let c=[...a.text];if(o+c.length<=l){i.push(a),o+=c.length;continue}let f=c.slice(0,l-o).join("");return i.push({...a,text:`${f}${n>=w(r)?r:""}`}),i}return i}var ee=18,te="  ";function ne(e,t,s){let n=e.isTTY===!0&&t.TERM!=="dumb"&&!t.CI&&t.BAKE_NO_ANIMATION!=="1",r=V(t),l=Q(t),i=Date.now(),o,a=!n,c=()=>(e.columns!==void 0&&e.columns>0?e.columns:80)-1-te.length,f=(d)=>`${te}${Z(d,r)}`,h=()=>{if(o===void 0)return;let d=Date.now();e.write(`\r\x1B[2K${f(z({label:o.label,...o.fraction===void 0?{}:{fraction:o.fraction},...o.detail===void 0?{}:{detail:o.detail}},{time:d-i,width:c(),glyphs:l,labelWidth:ee,elapsed:d-o.started}))}`)},g=(d)=>{if(o===void 0)return;let u=d==="done"?[...o.notes,G(Date.now()-o.started)]:[];e.write(`\r\x1B[2K${f(Y(d,d==="done"?o.done:o.label,u,{width:c(),glyphs:l,labelWidth:ee}))}
`),o=void 0};if(n)e.write(`${f(U(s,c(),l))}

`);let O=n?setInterval(h,W):void 0;O?.unref();let R=()=>{if(a)return!1;return a=!0,clearInterval(O),!0};return{animated:n,step(d,u){if(a)return;g("done"),o={label:d,done:u,started:Date.now(),notes:[],fraction:void 0,detail:void 0},h()},note(...d){if(!a)o?.notes.push(...d)},progress(d,u){if(a||o===void 0)return;o.fraction=d,o.detail=u},finish(d){if(!R())return;g("done"),e.write(`
${f(q(d.title,Date.now()-i,c(),l))}
`);for(let u of d.next??[])e.write(`${f(J(u,c(),l))}
`)},fail(){if(R())g("failed")},stop(){if(R()&&o!==void 0)e.write("\r\x1B[2K")}}}var[se,ge,he]=process.argv.slice(2);if(!se)throw Error("Missing installer progress file");var xe=Number(ge),T=ne(process.stderr,process.env,["installer",he??""]),C=process.env.HOME??process.env.USERPROFILE,be=(e)=>C!==void 0&&C!==""&&(e===C||e.startsWith(`${C}${oe.sep}`))?`~${e.slice(C.length)}`:e,X=(e)=>(e/1e6).toFixed(1),A=0,b,re=()=>{if(b!==void 0)T.note(`${X(b.total)} MB`);b=void 0},ye=([e="",...t])=>{switch(e){case"step":return re(),T.step(t[0]??"",t[1]??t[0]??""),!1;case"note":return T.note(...t.map(be)),!1;case"size":{let s=Number(t[1]);if(t[0]!==void 0&&t[0]!==""&&Number.isFinite(s)&&s>0)b={path:t[0],total:s};return!1}case"done":return re(),T.finish({title:t[0]??"",next:t.slice(1)}),!0;case"stop":return T.fail(),!0;default:return!1}},B=setInterval(()=>{try{process.kill(xe,0);let e=D.readFileSync(se,"utf8"),t=e.lastIndexOf(`
`)+1,s=e.slice(A,Math.max(A,t)).split(`
`).slice(0,-1);A=Math.max(A,t);for(let n of s)if(ye(n.replace(/\r$/u,"").split("\t"))){clearInterval(B);return}if(b!==void 0){let n=0;try{n=D.statSync(b.path).size}catch{}T.progress(Math.min(1,n/b.total),`${X(Math.min(n,b.total))} / ${X(b.total)} MB`)}}catch{clearInterval(B),T.fail()}},100);for(let e of["SIGINT","SIGTERM"])process.once(e,()=>{clearInterval(B),T.fail()});
// # END ANIMATION
ANIMATION
  : > "$temporary/progress"
  node "$temporary/animation.cjs" "$temporary/progress" "$$" "$target" &
  animation_pid=$!
fi
install_bake() {
report step 'Verifying release' 'Verified release'
curl -fsSL "$base_url/latest.json" -o "$temporary/latest.json"
curl -fsSL "$base_url/latest.json.sig" -o "$temporary/latest.json.sig"
node - "$temporary/latest.json" "$target" "$temporary/latest.json.sig" > "$temporary/selected" <<'NODE'
const fs = require('node:fs')
const crypto = require('node:crypto')
// The release signing key; BAKE_RELEASE_PUBLIC_KEY adds one for a local check.
const keys = ['MCowBQYDK2VwAyEAG1Z33Mis04XnFsekLrnPDBwSgn26uNeLz3XtGal+xC4=', process.env.BAKE_RELEASE_PUBLIC_KEY]
  .filter(key => typeof key === 'string' && key.trim() !== '')
const bytes = fs.readFileSync(process.argv[2])
const signature = Buffer.from(fs.readFileSync(process.argv[4], 'utf8').trim(), 'base64')
const signed = signature.length === 64 && keys.some(key => {
  try { return crypto.verify(null, bytes, crypto.createPublicKey({ key: Buffer.from(key.trim(), 'base64'), format: 'der', type: 'spki' }), signature) } catch { return false }
})
if (!signed) {
  console.error('The Bake release manifest signature did not verify.')
  process.exit(1)
}
const manifest = JSON.parse(bytes.toString('utf8'))
const target = process.argv[3]
const artifact = manifest.artifacts?.[target]
if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(manifest.version)
  || artifact?.file !== `bake-v${manifest.version}-${target}.tar.gz`
  || !/^[a-f0-9]{64}$/.test(artifact.sha256)) {
  console.error(`No valid Bake archive for ${target}`)
  process.exit(1)
}
console.log(manifest.version)
console.log(artifact.file)
console.log(artifact.sha256)
console.log(Number.isSafeInteger(artifact.size) && artifact.size > 0 ? artifact.size : '')
NODE
version=$(sed -n '1p' "$temporary/selected")
file=$(sed -n '2p' "$temporary/selected")
expected=$(sed -n '3p' "$temporary/selected")
size=$(sed -n '4p' "$temporary/selected")
digest_prefix=$(printf '%s' "$expected" | cut -c 1-12)
report note "v$version" signed
# A GitHub host serves each archive from its own tag; see archiveUrl in the updater.
case $base_url in
  https://github.com/*/*/releases/latest/download) archive_url="${base_url%/latest/download}/download/v$version/$file" ;;
  *) archive_url="$base_url/releases/$version/$file" ;;
esac
report step Downloading Downloaded
if [ -n "$size" ]; then report size "$temporary/$file" "$size"; fi
curl -fsSL "$archive_url" -o "$temporary/$file"
report step 'Checking SHA-256' 'Checked SHA-256'
if command -v shasum >/dev/null 2>&1; then
  actual=$(shasum -a 256 "$temporary/$file" | cut -d ' ' -f 1)
elif command -v sha256sum >/dev/null 2>&1; then
  actual=$(sha256sum "$temporary/$file" | cut -d ' ' -f 1)
else
  echo 'Bake install needs shasum or sha256sum.' >&2
  exit 1
fi
if [ "$actual" != "$expected" ]; then
  echo 'Bake download checksum did not match the release manifest.' >&2
  exit 1
fi
report note "$digest_prefix"

report step Installing Installed
mkdir -p "$install_root/versions" "$bin_dir" "$temporary/unpacked"
tar -xzf "$temporary/$file" -C "$temporary/unpacked"
node "$temporary/unpacked/apps/cli/lib/bin.js" --version >/dev/null
new_version="$install_root/versions/$version-$digest_prefix"
if [ -d "$new_version" ]; then
  node "$new_version/apps/cli/lib/bin.js" --version >/dev/null
else
  mv "$temporary/unpacked" "$new_version"
fi
ln -s "$new_version" "$install_root/.current-$$"
if [ -L "$install_root/current" ]; then
  rm "$install_root/current"
elif [ -e "$install_root/current" ]; then
  echo "$install_root/current exists and is not a Bake-managed link." >&2
  exit 1
fi
mv -f "$install_root/.current-$$" "$install_root/current"
report note "$new_version"
report step Linking Linked
ln -s "$install_root/current/bin/bake" "$bin_dir/.bake-$$"
if [ -L "$bin_dir/bake" ]; then
  rm "$bin_dir/bake"
elif [ -e "$bin_dir/bake" ]; then
  echo "$bin_dir/bake exists and is not a Bake-managed link." >&2
  exit 1
fi
mv -f "$bin_dir/.bake-$$" "$bin_dir/bake"
report note "$bin_dir/bake"

}
install_bake 2> "$temporary/errors"
case ":$PATH:" in
  *":$bin_dir:"*) next='Run: bake' ;;
  *) next="Add $bin_dir to PATH, then run: bake" ;;
esac
if [ -n "$animation_pid" ]; then
  stop_animation done "Bake $version installed" "$next"
else
  echo "Installed Bake $version at $new_version"
  echo "$next"
fi
