/** Terminal labels. Model, tool, and command text stays verbatim. */
export const dictionaries = {
  en: {
    attachFile: "Stage a file for the next prompt",
    attachUsage: "Usage: /attach <literal path>", attachHint: "<path>",
    removeAttachment: "Remove a staged attachment",
    removeAttachmentUsage: "Usage: /remove-attachment <displayed number>", removeAttachmentHint: "<number>",
    clearAttachments: "Discard staged attachments",
    clearAttachmentsUsage: "Usage: /clear-attachments",
    attachmentStaged: "Staged", attachmentRemoved: "Removed", attachmentsCleared: "Cleared",
    attachmentCountOne: "attachment", attachmentCountMany: "attachments",
    attachmentCountLimit: "Staged attachment count limit reached",
    attachmentsUnavailable: "This profile has no attachment or filesystem service",
    modelNoImages: "The selected model does not accept images",
    attachmentModelChanged: "Model changed during attachment admission; submit again",
    attachmentCommandsUnsupported: "Send or clear staged attachments before running this command",
    attachmentCancelled: "Attachment submission cancelled; draft retained",
    attachmentsBeforeNavigation: "Send or clear staged attachments before switching sessions",
    attachmentsTitle: "Staged attachments",
    attachmentsHelp: "Enter sends · /remove-attachment <number> removes · /clear-attachments clears",
    attachmentsSending: "Preparing attachments… Esc cancels",
    clipboardNoImage: "No image on the clipboard",
    clipboardImageTooLarge: "The clipboard image is larger than the attachment limit",
    imageStaging: "Still reading the pasted image; press Enter again",
    working: 'Working', stopping: 'Stopping', command: 'Command',
    compacting: 'Compacting history', compactPreparing: 'preparing', compactSummarizing: 'summarizing',
    compactSaving: 'saving', compactWait: 'Compacting… Enter queues · Esc cancels',
    goalActive: 'Goal active', goalHeld: 'Goal on hold', goalPaused: 'Goal paused', goalBlocked: 'Goal blocked',
    goalComplete: 'Goal complete', goalRound: 'round', goalResume: '/goal resume continues',
    goalTitle: 'Goal', goalReason: 'Reason', goalKey: 'Ctrl+O', goalOpen: 'Enter opens',
    sheetClose: 'Esc closes', sheetScroll: '↑↓ scroll', sheetCycle: 'Tab next', sheetSelect: '↑↓ select',
    sheetPages: 'PgUp/PgDn scroll',
    transcriptScroll: 'Wheel/PgUp/PgDn scroll · Ctrl+↑↓ prompts · Ctrl+Home first',
    selectionCopied: 'Copied', selectionCopyFailed: 'Copy failed',
    transcriptPaused: 'History · Ctrl+↑↓ prompts',
    transcriptLatest: '↓ Latest · Ctrl+End', transcriptUnseen: '↓ New output · Ctrl+End',
    goalObjective: 'Objective',
    // One word is chosen per turn. The words are `|`-separated so the dictionary stays flat strings.
    activityWords: 'Baking|Kneading|Proofing|Whisking|Simmering|Folding|Glazing|Rising|Preheating|Sifting|Toasting|Caramelizing',
    summaryFailed: 'Failed', summaryFailures: 'failed',
    phaseThinking: 'thinking', phaseWriting: 'writing', phaseRunning: 'running', scriptLabel: 'Script', scriptOutput: 'Script output', scriptError: 'Script error',
    scriptCall: 'call', scriptCalls: 'calls', moreCalls: 'more calls',
    pending: 'Pending input', nextStep: 'Next step', nextTurn: 'Next turn',
    pendingHelp: 'Alt+\u2191 sends it now', pendingSent: 'Sent queued input now', noPending: 'No queued input',
    pendingAfterCompaction: 'Queued input runs once compaction ends',
    // The idle placeholder's parts; the ones after the first yield whole on a narrow terminal.
    prompt: 'Ask anything', promptCommands: '/ commands', promptFiles: '@ files',
    composerAbove: 'above', composerBelow: 'below',
    welcomeHelp: 'list available commands', welcomeChangelog: 'see what changed in this version',
    // The welcome card's description column is 48 cells wide; this must fit it.
    newlineKey: 'Ctrl+J', welcomeNewline: 'new line · Shift+Enter: /terminal-setup',
    changelogCommand: 'Show what changed in this Bake version', changelogUsage: 'Usage: /changelog',
    changelogUnavailable: 'No changelog entry is available for this version',
    terminalSetupCommand: 'Make Shift+Enter insert a new line in this terminal', terminalSetupUsage: 'Usage: /terminal-setup',
    terminalSetupTitle: 'Set up Shift+Enter', terminalSetupAdds: 'Adds to', terminalSetupCreates: 'Creates',
    terminalSetupWrite: 'Write it', terminalSetupBackupFirst: 'backs the file up first', terminalSetupNewFile: 'a new file',
    terminalSetupCancel: 'Cancel', terminalSetupUnchanged: 'changes nothing',
    terminalSetupCancelled: 'Terminal setup cancelled; nothing changed',
    terminalSetupDone: 'Shift+Enter now inserts a new line', terminalSetupWrote: 'Updated', terminalSetupCreated: 'Created',
    terminalSetupBackup: 'Backed up the original to', terminalSetupUndo: 'To undo, run',
    terminalSetupLive: 'applies the change at once', terminalSetupTest: 'Press Shift+Enter in the prompt to try it',
    terminalSetupRestart: 'If Shift+Enter still submits, restart',
    terminalSetupReloadGhostty: 'Reload Ghostty\'s config to apply it: Ctrl+Shift+, (Cmd+Shift+, on macOS), or restart Ghostty',
    terminalSetupReloadKitty: 'Reload kitty\'s config to apply it: Ctrl+Shift+F5 (Ctrl+Cmd+, on macOS)',
    terminalSetupPresent: 'Shift+Enter already inserts a new line; nothing changed',
    terminalSetupConflict: 'Shift+Enter is already bound to something else; Bake left it unchanged',
    terminalSetupReplace: 'To make Shift+Enter insert a new line, replace that binding with:',
    terminalSetupUnreadable: 'Bake could not follow this file\'s syntax, so it changed nothing',
    terminalSetupManual: 'To set it up yourself, add this to', terminalSetupFailed: 'Could not write the file',
    terminalSetupNoFile: 'no settings.json where it keeps one',
    terminalSetupTmux: 'Inside tmux: this sets up the terminal around it',
    terminalSetupRemote: 'Bake runs on another machine; set this up in the terminal on your own:',
    terminalSetupUnknown: 'Bake cannot tell which terminal this is',
    terminalSetupGeneric: 'Set its Shift+Enter to send ESC CR (\\x1b\\r); Ctrl+J and Alt+Enter insert a new line anywhere',
    terminalSetupAlways: 'Ctrl+J inserts a new line in any terminal',
    terminalSetupEditorSteps: 'Run "Preferences: Open Keyboard Shortcuts (JSON)" from the Command Palette and add:',
    terminalSetupWindowsTerminal: 'In Windows Terminal, hold Shift and choose Settings to open settings.json, and add this to "actions":',
    terminalSetupWezterm: 'Add this to config.keys in ~/.wezterm.lua; WezTerm reloads it on save:',
    terminalSetupIterm: 'Settings → Profiles → Keys → Key Mappings → +: press Shift+Return, choose Send Hex Code, and enter 0x1b 0x0d',
    terminalSetupItermOption: 'For Option+Enter too: Settings → Profiles → Keys → General → Left Option key: Esc+',
    terminalSetupApple: 'Terminal sends Shift+Enter as a plain Enter. Turn on Settings → Profiles → Keyboard → '
      + 'Use Option as Meta key, and Option+Enter inserts a new line',
    terminalSetupAlacrittyYaml: 'this is a legacy alacritty.yml, which Bake does not edit; run alacritty migrate and '
      + '/terminal-setup again, or add this under key_bindings in',
    terminalSetupAlacrittyInline: 'this file lists its key bindings in one inline array, which Bake does not edit',
    updateCommand: 'Install the newest Bake release', updateUsage: 'Usage: /update',
    updateChecking: 'Checking for a newer Bake', updateDownloading: 'Downloading Bake', updateUnpacking: 'Unpacking Bake',
    updateVerifying: 'Checking the new release starts', updateCurrent: 'Bake is up to date',
    updateUnavailable: 'A newer Bake is published, but not yet for this platform',
    updateUnsupported: 'Bake publishes no release for this platform',
    updateUnmanaged: 'The updater does not manage this Bake',
    updateUnmanagedHint: 'a source checkout updates with git pull && bun install --frozen-lockfile && bun run build; any other copy by installing again',
    updateInstalled: 'Bake updated; new sessions start it, and this one keeps running', updateRestart: 'restart to use',
    updateFailed: 'Update failed', updateCancelled: 'Update cancelled; the install is unchanged',
    preview: 'Preview', previewReplaying: 'Replaying', previewPrompt: 'Try the composer', previewSend: 'Enter previews',
    previewHelp: 'Component preview · No agent connected\nReal chat: bun run dev:tui',
    previewAccepted: 'Preview message displayed; no agent is connected.',
    interrupt: 'Esc interrupts',
    editHelp: '←→ move · Ctrl/Alt+←→ word · Home/End row, then line · ↑↓ rows, then history · Ctrl+W/Alt+D delete word · Ctrl+U/K delete to line edge · Ctrl+Y paste back · Ctrl+- undo · Ctrl+J or Alt+Enter new line · Shift+Enter: /terminal-setup · Ctrl+V image · Shift+Tab thinking',
    steering: 'Enter steers the next step · Alt+\u2191 sends now', quit: 'Press Ctrl-C again to quit',
    approval: 'Approval required', approve: 'Y allows once · N rejects',
    questions: 'Answer required', customAnswer: 'Other answer', customAnswerHint: 'type your own answer',
    questionSelected: 'selected', questionChooseOne: 'Tick at least one option, or type your own answer',
    questionTypeFirst: 'Type an answer first, or choose an option',
    questionPickerHelp: '↑↓ choose · 1-9 jumps · Enter selects · type to answer · Esc cancels',
    multiPickerHelp: '↑↓ choose · Space ticks · Enter submits · type to answer · Esc cancels',
    questionDetailHelp: 'PgUp/PgDn read more',
    cancelled: 'Interrupted', compacted: 'Context compacted',
    // A hook or tool policy halted the turn; its recorded reason follows.
    turnHalted: 'Stopped by a hook',
    turn: 'Turn', turnCompleted: 'Completed', turnBlocked: 'Blocked', turnMaxTokens: 'Output token limit reached',
    cardLine: 'line', cardLines: 'lines', cardMatch: 'match', cardMatches: 'matches',
    cardPath: 'path', cardPaths: 'paths', cardSource: 'source', cardSources: 'sources',
    cardTruncated: 'capped',
    // A command's changed files: the word after a path, and the section's counts and caveats.
    changeNew: 'new', changeDeleted: 'deleted', changeRenamed: 'renamed from', changeBinary: 'binary',
    changeTooLarge: 'too large', changeMode: 'mode', changeSymlink: 'symlink',
    changeConcurrent: 'may include other activity', changeTimedOut: 'may be incomplete',
    cardFiles: 'files', moreFile: 'more file', moreFiles: 'more files',
    unknownCommand: 'Unknown command', commandBusy: 'A command is already running',
    didYouMean: 'did you mean', unknownCommandHint: 'start with a space to send it as a message',
    usage: 'Usage', helpHint: '[command]', helpFooter: 'Type / to browse · /help <command> shows one command · Tab completes',
    aliasOf: 'Same as',
    chooseSession: 'Choose session', newSession: 'New session', untitledSession: 'Untitled session', resumeSession: 'Browse sessions or start a new one',
    ageNow: 'just now', ageMinutes: 'm ago', ageHours: 'h ago', ageDays: 'd ago',
    newSessionCommand: 'Start a new session; this one stays saved',
    sessionsLoading: 'Loading sessions…', sessionOpening: 'Opening session…',
    sessionsIdle: 'Finish or interrupt the turn before switching sessions',
    sessionsPending: 'Queued input must run before switching sessions; Alt+\u2191 sends it now',
    sessionsBusy: 'Session navigation is in progress', sessionsCancelled: 'Session navigation cancelled',
    sessionsError: 'Session navigation failed', sessionTitlesUnavailable: 'Some session titles are unavailable; select by id',
    sessionInUse: 'This session is open in another Bake process; close it there to continue it here, or start a new session with /new',
    sessionInUseLaunch: 'open in another Bake process; close it there and run this command again, or leave out --resume to start a new session',
    sessionNeedsPreset: 'This session has no recorded preset; resume it from the command line with --resume and --preset instead',
    session: 'Session', cancelHelp: 'Esc cancels',
    noCredentials: 'Nothing is signed in yet; type /login to choose a provider',
    signIn: 'Sign in or set up CLIProxyAPI', loginHint: '[target]',
    signOut: 'Remove a stored key or the CLIProxyAPI route', logoutHint: '[target]',
    listSubagents: 'List delegated agents', agentsUsage: 'Usage: /agents [id]',
    subagentsTitle: 'Subagents', subagentsOpen: 'Enter opens', subagentsKey: 'Ctrl+G', noSubagents: 'No subagents in this session',
    subagentsUnavailable: 'This profile has no subagent service',
    subagentCompleted: 'Completed', subagentFailed: 'Failed', subagentStopped: 'Stopped',
    subagentWorking: 'Working', subagentLive: 'Live', subagentSaved: 'Saved', subagentOneShot: 'One-shot',
    subagentContinuable: 'Continuable', subagentIssue: 'Unreadable child', subagentUnreadable: 'unreadable',
    subagentRoutingAuto: 'Auto', subagentRoutingDefault: 'Default', subagentRoutingSelected: 'Selected',
    subagentRoutingCautious: 'cautious', subagentRoutingNeedsContext: 'needs context', subagentRoutingFallback: 'fallback',
    subagentRoutingDifficulty: 'Difficulty',
    // Counts on the subagents row and its tab, lowercase like every standing row's state.
    subagentCountWorking: 'working', subagentCountDone: 'done', subagentCountFailed: 'failed', subagentCountStopped: 'stopped',
    subagentRemote: 'Remote run', subagentNoTranscript: 'No local transcript available',
    subagentChoose: 'Select a child to view its session. The parent keeps running.',
    subagentBack: 'Read-only · Esc returns to parent', subagentParent: 'Parent',
    // The bar under the input while a child's session is open.
    subagentReadOnly: 'Read-only', subagentBackKey: 'Esc back to parent',
    // Background work: the tag on the call that started it, how it ended, and its row under the input.
    backgroundTag: 'background', backgroundTitle: 'Background', backgroundRunning: 'running',
    jobFinished: 'finished', jobFailed: 'failed', jobStopped: 'stopped',
    chooseLogin: 'Choose a sign-in target', cliProxySetupHint: 'URL + API key',
    chooseLogout: 'Choose what to sign out of', chooseMethod: 'Choose how to sign in',
    routeNeeded: 'signed in; add it under llm-pi-ai providers in settings.yaml to use its models',
    nowUsing: 'now using', signedIn: 'signed in', modelsReady: 'models ready', modelReady: 'model ready',
    // No provider is chosen until one is signed in.
    noModel: 'no model', noModelHint: '/login to start',
    noModelSubmit: 'No model is selected yet: sign in with /login, or choose one with /model',
    cliProxyReady: 'models ready; choose one with /model', cliProxyReadyOne: 'model ready; choose it with /model',
    // The sign-in panel: its heading, its keys, and why an answer was refused.
    signInTitle: 'Sign in', loginHelp: 'Enter continues · Esc cancels', loginRetryHelp: 'Enter tries again · Esc cancels',
    loginEmpty: 'Type or paste a value, or press Esc to cancel',
    apiKey: 'API key', keyStoredLocally: 'saved in Bake\'s credential store, never in the session',
    keyInvalid: 'That key contains spaces or characters an HTTP header cannot carry; paste the key alone',
    cliProxyUrl: 'Base URL', cliProxyKey: 'API key',
    cliProxyUrlHint: 'The proxy root, /v1, or /backend-api address; leave it empty for the default',
    cliProxyChecking: 'Checking models at',
    cliProxyBadUrl: 'Enter an http(s) address such as http://127.0.0.1:8317, without a query, fragment, or credentials',
    cliProxyUnreachable: 'Could not reach', cliProxyTimeout: 'No answer within 15 seconds from',
    cliProxyRedirect: 'The address redirects elsewhere; enter the address it redirects to',
    cliProxyRejected: 'The proxy rejected this API key', cliProxyNotFound: 'No CLIProxyAPI model list at this address',
    cliProxyStatus: 'The proxy answered', cliProxyNotProxy: 'This address did not answer with a CLIProxyAPI model list',
    cliProxyTooLarge: 'The proxy\'s model list is too large to read',
    cliProxyEmpty: 'The proxy lists no chat models yet; add an upstream account to it, then try again',
    cliProxyUpgraded: 'Updated the CLIProxyAPI route for this version: ',
    cliProxyRelogin: 'The CLIProxyAPI route is from an earlier version and could not be updated; run /login cliproxyapi for: ',
    cliProxyChangeSeparator: ', ',
    cliProxyChangeProtocols: 'Claude over Anthropic Messages and chat-only models over Chat Completions',
    cliProxyChangeAdaptive: 'adaptive thinking for Claude', cliProxyChangeRetry: 'waiting out account cooldowns',
    cliProxyChangeAffinity: 'one account per session',
    noTargets: 'This profile has no sign-in targets', configured: 'Configured',
    notSet: 'Not set', readOnly: 'Read-only', stored: 'Stored; the next request uses it',
    fromEnvironment: 'From environment',
    setElsewhere: 'comes from the environment or a .env file; change or unset it there',
    loginCancelled: 'Sign-in cancelled', unknownTarget: 'Unknown sign-in target',
    logoutCancelled: 'Sign-out cancelled', unknownLogoutTarget: 'Unknown sign-out target',
    nothingToSignOut: 'Nothing to sign out of: no key or route is stored', keyRemoved: 'key removed',
    cliProxyRemoved: 'route and key removed', flowRemoved: 'signed out',
    modelNeedsProvider: 'the current model used it; choose another with /model',
    // Under a turn that failed for want of a usable key.
    missingCredentialHint: 'Run /login to add a key, or /model to switch to a configured provider',
    authFailedHint: 'Run /login to replace the key',
    // Status-line labels: lowercase and colon-free, each a dim word before its value.
    context: 'ctx', think: 'think', tokensIn: 'in', tokensOut: 'out', cacheHit: 'cache hit', updateLabel: 'update',
    contextCompactsAt: 'compacts at', contextCompactsNext: 'compacts next',
    permission: 'Access', thinking: 'Think', rateUnit: 'tok/s', listCommands: 'List available commands',
    selectModel: 'Choose model and reasoning effort', modelHint: '[provider/model [effort]]', modelSelected: 'Model set for the next turn',
    unknownModel: 'Unknown model', unknownEffort: 'Unknown reasoning effort; this model offers',
    modelBusy: 'Finish or interrupt the turn before changing model; /thinking or Shift+Tab changes reasoning effort now',
    thinkingCommand: 'Change reasoning effort, also during a turn', thinkingHint: '[effort|default]',
    thinkingTitle: 'Reasoning effort', thinkingCancelled: 'Reasoning effort unchanged', thinkingUsage: 'Usage: /thinking [effort|default]',
    thinkingLoading: 'Reasoning efforts are still loading', thinkingUnsupported: 'No reasoning efforts for', thinkingNextStep: 'from the next step',
    noModelSelection: 'This session has no model selection',
    modelSheet: 'Model', modelsFrom: 'from', listSeparator: ', ', recentModels: 'Recent', providerDefault: 'Provider default',
    factThink: 'think', factImage: 'image', effortLevels: 'Effort', effortDefault: 'Default', noEffort: 'not offered',
    modelSheetHelp: '↑↓ choose · ←→ effort · Enter selects · Esc cancels',
    currentSelection: 'Current', noChoices: 'No matching choices',
    pickerHelp: '↑↓ choose · Enter selects · Esc cancels', pickerFilter: 'Type to filter', pickerMore: 'more',
    pickerTabsHelp: 'Tab/⇧Tab switch section · ↑↓ choose · Enter selects · Esc back',
    modelsLoading: 'Loading models…', modelCatalogError: 'Unavailable model catalogs',
    modelCancelled: 'Model selection cancelled', modelUsage: 'Usage: /model [provider/model [effort]]',
    completionTitle: 'Commands and skills', completionHelp: '↑↓ choose · Tab completes · Esc closes', send: 'Enter sends',
    moreMatches: 'more, keep typing to narrow', moreLines: 'more lines', earlierCalls: 'earlier calls', attemptDiscarded: 'discarded: the text above was not kept', tabCompletes: 'Tab completes',
    unhandledRejection: 'Internal error', unhandledRejectionContinues: 'the session continues', unhandledRejectionRecord: 'details in',
    filesTitle: 'Workspace files', file: 'File', directory: 'Directory', noFiles: 'No matching paths',
    filesLoading: 'Finding paths…', filesError: 'File discovery failed', filesUnavailable: 'This profile has no file-reference provider',
    skill: 'Skill', catalogLoading: 'Loading skills…', catalogError: 'Skill discovery failed',
    catalogIncomplete: 'Some skill providers are unavailable', noCompletions: 'No matching commands or skills',
    settingsCommand: 'Change terminal and session settings', settingsUsage: 'Usage: /settings', settingsTitle: 'Settings',
    settingsSaved: 'Settings saved to', settingsStored: 'Settings saved', settingsUnsaved: 'No settings file; changes last until exit',
    settingsNextLaunch: 'Next launch', settingsNewSessions: 'New sessions', settingsByFlag: 'Set by --screen', settingsFailed: 'Settings not saved',
    settingsOn: 'On', settingsOff: 'Off',
    settingsScreen: 'Screen', settingsScreenInline: 'Inline, in terminal scrollback', settingsScreenFullscreen: 'Fullscreen, scrollable transcript',
    settingsFrame: 'Borders', settingsFrameAuto: 'Detect from terminal', settingsFrameRound: 'Rounded', settingsFrameClassic: 'ASCII',
    settingsGoalObjective: 'Goal objective on header', settingsResultLines: 'Tool output lines',
    settingsCompletionLimit: 'Menu rows', settingsDoubleInterrupt: 'Ctrl+C quit window', settingsPermission: 'Default access',
    settingsModel: 'Default model', settingsDefault: 'Default', settingsResultLinesNone: 'None, headline only',
    settingsResetSection: 'Reset this section to defaults', settingsResetConfirm: 'Reset every setting in this section to its default?',
    settingsResetKeep: 'Keep my settings', settingsResetDo: 'Reset to defaults', settingsResetField: 'Reset to default',
    settingsSession: 'Session', settingsTerminal: 'Terminal', settingsAgent: 'Agent', settingsRouting: 'Routing', settingsShell: 'Shell',
    settingsWeb: 'Web search', settingsAdvanced: 'Advanced',
    settingsField: 'setting', settingsFields: 'settings', settingsCustom: 'Enter a value…', settingsInFile: 'Edit in the settings file',
    settingsInEditor: 'Enter opens your editor', settingsEditorFailed: 'Editor did not save', settingsNotJson: 'Not valid JSON',
    settingsSecretSet: 'Set', settingsSecretUnset: 'Not set', settingsEmpty: 'Empty',
    settingsNotNumber: 'Not a number', settingsBelowMin: 'At least', settingsAboveMax: 'At most', settingsNotStep: 'In steps of',
    settingsDurationHint: 'e.g. 30s, 2m, 500ms', settingsBytesHint: 'e.g. 64KB, 1MB',
    settingsParallelTools: 'Parallel tool calls', settingsSubagentsActive: 'Subagents running at once',
    settingsSubagentDepth: 'Subagent nesting depth', settingsSubagentDepthOff: 'Off, no subagents',
    settingsSubagentModels: 'Subagents may pick a model', settingsShellTimeout: 'Command timeout',
    settingsSubagentAllowed: 'Models subagents may use', settingsSubagentAllowedNone: 'None chosen',
    settingsSubagentAllowedOn: 'Allowed', settingsSubagentAllowedDone: 'Done',
    settingsSubagentAllowedFirst: 'Choose at least one model to turn this on; Enter adds or removes one',
    settingsSubagentAllowedLast: 'Keep one model, or turn off Subagents may pick a model first',
    settingsRouter: 'Auto routing (beta)',
    settingsRouterAbout: 'Beta. When a delegation names no model, Bake sends its task text and the names of the models subagents may use to the router, which picks one and its effort. Your own providers still run every model',
    settingsRouterTurnOn: 'Turn on', settingsRouterKeepOff: 'Keep off', settingsRouterSignInTurnOn: 'Sign in and turn on',
    settingsRouterAccount: 'Router account', settingsRouterSignedOut: 'Not signed in', settingsRouterSignedIn: 'Signed in',
    settingsRouterSignedInAs: 'Signed in as', settingsRouterTokenFrom: 'Token from',
    settingsRouterNoStore: 'Signing in needs a credential store; set the token in',
    settingsRouterSwitch: 'Sign in with another email', settingsRouterSignOut: 'Sign out',
    settingsRouterEmail: 'Email', settingsRouterEmailHint: 'The router emails a six-digit code; a first sign-in creates your account',
    settingsRouterCode: 'Code sent to', settingsRouterCodeHint: 'Check your inbox; the code expires in ten minutes',
    settingsRouterUrl: 'Router URL', settingsRouterPriority: 'Routing priority', settingsRouterPriorityInfer: 'From the task',
    settingsRouterQualityPriority: 'Quality', settingsRouterCostPriority: 'Cost', settingsRouterSpeedPriority: 'Speed',
    settingsRouterBalanced: 'Balanced',
    settingsRouterCalibrate: 'Model calibration', settingsRouterCalibrateAbout: 'How the router sees each model',
    settingsRouterRanked: 'Ranked', settingsRouterUnranked: 'Needs a hint', settingsRouterUnknown: 'unknown to the router',
    settingsRouterNoneRanked: 'No model is ranked yet, so routed delegations keep the default model until one has a quality tier or a same-as model',
    settingsRouterUnavailable: 'Router unavailable', settingsRouterHinted: 'hint', settingsRouterQualityShort: 'quality', settingsRouterBenchmarksWin: 'benchmarks used over the quality tier',
    settingsRouterInherited: 'inherited estimate',
    settingsRouterQuality: 'Quality tier', settingsRouterCost: 'Cost tier', settingsRouterSameAs: 'Same as',
    settingsRouterAuto: 'Router decides', settingsRouterNone: 'None',
    settingsRouterSameAsPrompt: 'Benchmarked model this route serves, e.g. claude-opus-4.5; empty clears it',
    settingsTierLow: 'Low', settingsTierMedium: 'Medium', settingsTierHigh: 'High', settingsTierFrontier: 'Frontier',
    settingsTierFree: 'Free',
    settingsShellMaxTimeout: 'Longest timeout a command may ask for', settingsShellOutput: 'Command output kept in memory',
    settingsWebUses: 'Searches per request', settingsWebModel: 'Search model', settingsWebTokens: 'Search answer token limit',
    settingsCompaction: 'Compaction', settingsCompactionAuto: 'Automatic compaction',
    settingsCompactionAutoAbout: 'Summarize older history as the context fills, and retry a request that overflows it',
    settingsCompactionAt: 'Compact at', settingsCompactionAtAbout: 'How full the context window gets before older history is summarized',
    settingsCompactionKeep: 'Keep recent', settingsCompactionKeepAbout: 'Recent history kept word for word after a summary',
    settingsCompactionKeepBelow: 'Keep recent must be less than Compact at',
    settingsCompactionModel: 'Summary model', settingsCompactionSameModel: 'Same as the session',
    settingsCompactionLimit: 'Summary length limit', settingsCompactionRules: 'Per-model rules',
    settingsCompactionRulesAbout: 'Compact at and Keep recent for one provider or model, as a JSON list',
    settingsCompactionRulesNone: 'None', settingsCompactionRule: 'rule', settingsCompactionRuleCount: 'rules',
    settingsOfContext: 'of context', settingsTokens: 'tokens',
    settingsBudgetHint: 'e.g. 75% or 150k tokens', settingsBudgetInvalid: 'Enter a percent such as 75%, or tokens such as 150k',
    settingsTokensHint: 'e.g. 8k, 16000', settingsRouteHint: 'provider/model; empty uses the session model',
    settingsRouteInvalid: 'Enter provider/model',
    settingsChanged: 'Changed', settingsDefaultIs: 'default', settingsChangedCount: 'changed', settingsNotSet: 'Not set',
    settingsScreenAbout: 'Inline keeps the conversation in terminal scrollback; fullscreen gives it a scrollable view of its own',
    settingsFrameAbout: 'How the input and panels are framed',
    settingsGoalObjectiveAbout: 'Name the goal\u2019s objective on the header after its state',
    settingsResultLinesAbout: 'Lines of a tool\u2019s output shown under its call',
    settingsCompletionLimitAbout: 'Rows a menu shows before it scrolls',
    settingsDoubleInterruptAbout: 'How soon a second Ctrl+C must follow the first to quit',
    settingsModelAbout: 'The model and effort new sessions start on; choosing one also switches this session',
    settingsPermissionAbout: 'What the agent may do without asking, in new sessions',
    settingsParallelToolsAbout: 'Tool calls from one response that run at the same time',
    settingsSubagentsActiveAbout: 'Subagents that may run at the same time',
    settingsSubagentDepthAbout: 'How deep subagents may start subagents of their own',
    settingsSubagentModelsAbout: 'Let the agent choose a model for each subagent from the models below',
    settingsSubagentAllowedAbout: 'Models a subagent may be given; Enter adds or removes one',
    settingsShellTimeoutAbout: 'How long a command runs before it is stopped, unless it asks for longer',
    settingsShellMaxTimeoutAbout: 'The longest a command may ask to run',
    settingsShellOutputAbout: 'How much of a command\u2019s output is kept',
    settingsWebUsesAbout: 'Web searches the model may make in one request',
    settingsWebModelAbout: 'The model that answers web searches',
    settingsWebTokensAbout: 'The longest answer a web search may return',
    settingsCompactionModelAbout: 'The model that writes the summary; the session\u2019s own unless you choose another',
    settingsCompactionLimitAbout: 'The longest summary the model may write',
  },
} as const

/** Labels supplied to presentation components by the application. */
export type TuiCopy = { readonly [K in keyof typeof dictionaries.en]: string }
