/** Locale-owned terminal labels. Model, tool, and command text stays verbatim. */
export const dictionaries = {
  en: {
    attachFile: "Stage a file for the next prompt",
    attachUsage: "Usage: /attach <literal path>", attachHint: "<path>",
    removeAttachment: "Remove a staged attachment",
    removeAttachmentUsage: "Usage: /remove-attachment <displayed number>", removeAttachmentHint: "<number>",
    clearAttachments: "Discard staged attachments",
    clearAttachmentsUsage: "Usage: /clear-attachments",
    attachmentStaged: "Staged", attachmentRemoved: "Removed", attachmentsCleared: "Cleared",
    attachmentCountOne: "attachment", attachmentCountMany: "attachments",
    attachmentCountLimit: "Staged attachment count limit reached",
    attachmentsUnavailable: "This profile has no attachment or filesystem service",
    modelNoImages: "The selected model does not accept images",
    attachmentModelChanged: "Model changed during attachment admission; submit again",
    attachmentCommandsUnsupported: "Send or clear staged attachments before running this command",
    attachmentCancelled: "Attachment submission cancelled; draft retained",
    attachmentsBeforeNavigation: "Send or clear staged attachments before switching sessions",
    attachmentsTitle: "Staged attachments",
    attachmentsHelp: "Enter sends · /remove-attachment <number> removes · /clear-attachments clears",
    attachmentsSending: "Preparing attachments… Esc cancels",
    working: 'Working', stopping: 'Stopping', command: 'Command',
    compacting: 'Compacting history', compactPreparing: 'preparing', compactSummarizing: 'summarizing',
    compactSaving: 'saving', compactWait: 'Compacting… Enter queues · Esc cancels',
    planActive: 'Plan', planEntryPending: 'Plan pending', planExitPending: 'Plan exit pending',
    goalActive: 'Goal active', goalHeld: 'Goal on hold', goalPaused: 'Goal paused', goalBlocked: 'Goal blocked',
    goalComplete: 'Goal complete', goalRound: 'round', goalResume: '/goal resume continues',
    goalTitle: 'Goal', goalReason: 'Reason', goalKey: 'Ctrl+O', goalOpen: 'Enter opens',
    sheetClose: 'Esc closes', sheetScroll: '↑↓ scroll', sheetCycle: 'Tab next', sheetSelect: '↑↓ select',
    transcriptScroll: 'Wheel/PgUp/PgDn scroll · Ctrl+Home first · Ctrl+End latest',
    transcriptPaused: 'History · Wheel/PgUp/PgDn scroll',
    transcriptLatest: '↓ Latest · Ctrl+End', transcriptUnseen: '↓ New output · Ctrl+End',
    goalObjective: 'Objective', todoActive: 'in progress', todoLeft: 'left',
    // One word is chosen per turn. The words are `|`-separated so the dictionary stays flat strings.
    activityWords: 'Baking|Kneading|Proofing|Whisking|Simmering|Folding|Glazing|Rising|Preheating|Sifting|Toasting|Caramelizing',
    summaryFailed: 'Failed', summaryFailures: 'failed',
    phaseThinking: 'thinking', phaseWriting: 'writing', phaseRunning: 'running',
    pending: 'Pending input', nextStep: 'Next step', nextTurn: 'Next turn',
    clearPending: 'Discard queued input', clearPendingUsage: 'Usage: /clear-pending',
    pendingHelp: '/clear-pending discards queued input', pendingCleared: 'Queued input discarded', noPending: 'No queued input',
    // The idle placeholder's parts; the ones after the first yield whole on a narrow terminal.
    prompt: 'Ask anything', promptCommands: '/ commands', promptFiles: '@ files',
    composerAbove: 'above', composerBelow: 'below',
    welcomeHelp: 'list available commands', welcomeChangelog: 'see what changed in this version',
    // The welcome card's description column is 48 cells wide; this must fit it.
    newlineKey: 'Ctrl+J', welcomeNewline: 'new line · Shift+Enter: /terminal-setup',
    changelogCommand: 'Show what changed in this Bake version', changelogUsage: 'Usage: /changelog',
    changelogUnavailable: 'No changelog entry is available for this version',
    terminalSetupCommand: 'Make Shift+Enter insert a new line in this terminal', terminalSetupUsage: 'Usage: /terminal-setup',
    terminalSetupTitle: 'Set up Shift+Enter', terminalSetupAdds: 'Adds to', terminalSetupCreates: 'Creates',
    terminalSetupWrite: 'Write it', terminalSetupBackupFirst: 'backs the file up first', terminalSetupNewFile: 'a new file',
    terminalSetupCancel: 'Cancel', terminalSetupUnchanged: 'changes nothing',
    terminalSetupCancelled: 'Terminal setup cancelled; nothing changed',
    terminalSetupDone: 'Shift+Enter now inserts a new line', terminalSetupWrote: 'Updated', terminalSetupCreated: 'Created',
    terminalSetupBackup: 'Backed up the original to', terminalSetupUndo: 'To undo, run',
    terminalSetupLive: 'applies the change at once', terminalSetupTest: 'Press Shift+Enter in the prompt to try it',
    terminalSetupRestart: 'If Shift+Enter still submits, restart',
    terminalSetupReloadGhostty: 'Reload Ghostty\'s config to apply it: Ctrl+Shift+, (Cmd+Shift+, on macOS), or restart Ghostty',
    terminalSetupReloadKitty: 'Reload kitty\'s config to apply it: Ctrl+Shift+F5 (Ctrl+Cmd+, on macOS)',
    terminalSetupPresent: 'Shift+Enter already inserts a new line; nothing changed',
    terminalSetupConflict: 'Shift+Enter is already bound to something else; Bake left it unchanged',
    terminalSetupReplace: 'To make Shift+Enter insert a new line, replace that binding with:',
    terminalSetupUnreadable: 'Bake could not follow this file\'s syntax, so it changed nothing',
    terminalSetupManual: 'To set it up yourself, add this to', terminalSetupFailed: 'Could not write the file',
    terminalSetupNoFile: 'no settings.json where it keeps one',
    terminalSetupTmux: 'Inside tmux: this sets up the terminal around it',
    terminalSetupRemote: 'Bake runs on another machine; set this up in the terminal on your own:',
    terminalSetupUnknown: 'Bake cannot tell which terminal this is',
    terminalSetupGeneric: 'Set its Shift+Enter to send ESC CR (\\x1b\\r); Ctrl+J and Alt+Enter insert a new line anywhere',
    terminalSetupAlways: 'Ctrl+J inserts a new line in any terminal',
    terminalSetupEditorSteps: 'Run "Preferences: Open Keyboard Shortcuts (JSON)" from the Command Palette and add:',
    terminalSetupWindowsTerminal: 'In Windows Terminal, hold Shift and choose Settings to open settings.json, and add this to "actions":',
    terminalSetupWezterm: 'Add this to config.keys in ~/.wezterm.lua; WezTerm reloads it on save:',
    terminalSetupIterm: 'Settings → Profiles → Keys → Key Mappings → +: press Shift+Return, choose Send Hex Code, and enter 0x1b 0x0d',
    terminalSetupItermOption: 'For Option+Enter too: Settings → Profiles → Keys → General → Left Option key: Esc+',
    terminalSetupApple: 'Terminal sends Shift+Enter as a plain Enter. Turn on Settings → Profiles → Keyboard → '
      + 'Use Option as Meta key, and Option+Enter inserts a new line',
    terminalSetupAlacrittyYaml: 'this is a legacy alacritty.yml, which Bake does not edit; run alacritty migrate and '
      + '/terminal-setup again, or add this under key_bindings in',
    terminalSetupAlacrittyInline: 'this file lists its key bindings in one inline array, which Bake does not edit',
    updateCommand: 'Install the newest Bake release', updateUsage: 'Usage: /update',
    updateChecking: 'Checking for a newer Bake…', updateDownloading: 'Downloading Bake', updateUnpacking: 'Unpacking Bake',
    updateVerifying: 'Checking the new release starts', updateCurrent: 'Bake is up to date',
    updateUnavailable: 'A newer Bake is published, but not yet for this platform',
    updateUnsupported: 'Bake publishes no release for this platform',
    updateUnmanaged: 'The updater does not manage this Bake',
    updateUnmanagedHint: 'a source checkout updates with git pull && bun install --frozen-lockfile && bun run build; any other copy by installing again',
    updateInstalled: 'Bake updated; new sessions start it, and this one keeps running', updateRestart: 'restart to use',
    updateFailed: 'Update failed', updateCancelled: 'Update cancelled; the install is unchanged',
    preview: 'Preview', previewReplaying: 'Replaying', previewPrompt: 'Try the composer', previewSend: 'Enter previews',
    previewHelp: 'Component preview · No agent connected\nReal chat: bun run dev:tui',
    previewAccepted: 'Preview message displayed; no agent is connected.',
    interrupt: 'Esc interrupts',
    editHelp: '←→ move · Home/End line · ↑↓ rows, then history · Ctrl+J or Alt+Enter new line · Shift+Enter: /terminal-setup',
    steering: 'Enter steers the next step', quit: 'Press Ctrl-C again to quit',
    approval: 'Approval required', approve: 'Y allows once · N rejects',
    questions: 'Answer required', customAnswer: 'Other answer', customAnswerHint: 'type your own answer',
    questionSelected: 'selected', questionChooseOne: 'Tick at least one option, or type your own answer',
    questionTypeFirst: 'Type an answer first, or choose an option',
    questionPickerHelp: '↑↓ choose · 1-9 jumps · Enter selects · type to answer · Esc cancels',
    multiPickerHelp: '↑↓ choose · Space ticks · Enter submits · type to answer · Esc cancels',
    cancelled: 'Interrupted', compacted: 'Context compacted',
    turn: 'Turn', turnCompleted: 'Completed', turnBlocked: 'Blocked', turnMaxTokens: 'Output token limit reached',
    cardLine: 'line', cardLines: 'lines', cardMatch: 'match', cardMatches: 'matches',
    cardPath: 'path', cardPaths: 'paths', cardSource: 'source', cardSources: 'sources',
    cardTruncated: 'capped',
    todoTitle: 'Tasks', todoDone: 'done', todoKey: 'Ctrl+T', todoOpen: 'Enter opens',
    unknownCommand: 'Unknown command', commandBusy: 'A command is already running',
    didYouMean: 'did you mean', unknownCommandHint: 'start with a space to send it as a message',
    usage: 'Usage', helpHint: '[command]', helpFooter: 'Type / to browse · /help <command> shows one command · Tab completes',
    aliasOf: 'Same as',
    chooseSession: 'Choose session', newSession: 'New session', untitledSession: 'Untitled session', resumeSession: 'Browse sessions or start a new one',
    ageNow: 'just now', ageMinutes: 'm ago', ageHours: 'h ago', ageDays: 'd ago',
    newSessionCommand: 'Start a new session; this one stays saved',
    sessionsLoading: 'Loading sessions…', sessionOpening: 'Opening session…',
    sessionsIdle: 'Finish or interrupt the turn before switching sessions',
    sessionsPending: 'Queued input must be consumed or cleared before switching sessions',
    sessionsBusy: 'Session navigation is in progress', sessionsCancelled: 'Session navigation cancelled',
    sessionsError: 'Session navigation failed', sessionTitlesUnavailable: 'Some session titles are unavailable; select by id',
    sessionInUse: 'This session is open in another Bake process; close it there to continue it here, or start a new session with /new',
    sessionInUseLaunch: 'open in another Bake process; close it there and run this command again, or leave out --resume to start a new session',
    sessionNeedsPreset: 'This session has no recorded preset; resume it from the command line with --resume and --preset instead',
    session: 'Session', cancelHelp: 'Esc cancels',
    noCredentials: 'No credential is configured; type /login to set one',
    signIn: 'Sign in or set up CLIProxyAPI', loginHint: '[target]', pasteCredential: 'Paste the credential value',
    listSubagents: 'List delegated agents', agentsUsage: 'Usage: /agents [id]',
    subagentsTitle: 'Subagents', subagentsOpen: 'Enter opens', subagentsKey: 'Ctrl+G', noSubagents: 'No subagents in this session',
    subagentsUnavailable: 'This profile has no subagent service',
    subagentCompleted: 'Completed', subagentFailed: 'Failed', subagentStopped: 'Stopped',
    subagentWorking: 'Working', subagentLive: 'Live', subagentSaved: 'Saved', subagentOneShot: 'One-shot',
    subagentContinuable: 'Continuable', subagentIssue: 'Unreadable child', subagentUnreadable: 'unreadable',
    // Counts on the subagents row and its tab, lowercase like every standing row's state.
    subagentCountWorking: 'working',
    subagentRemote: 'Remote run', subagentNoTranscript: 'No local transcript available',
    subagentChoose: 'Select a child to view its session. The parent keeps running.',
    subagentBack: 'Read-only · Esc returns to parent', subagentParent: 'Parent',
    chooseLogin: 'Choose a sign-in target', cliProxySetupHint: 'URL + API key',
    cliProxyReady: 'models ready; choose one with /model', cliProxyReadyOne: 'model ready; choose it with /model',
    loginHelp: 'Enter continues · Esc cancels',
    cliProxyUrl: 'CLIProxyAPI base URL', cliProxyKey: 'CLIProxyAPI API key',
    cliProxyChecking: 'Checking CLIProxyAPI models…',
    cliProxyUpgraded: 'Updated the CLIProxyAPI route for this version: ',
    cliProxyRelogin: 'The CLIProxyAPI route is from an earlier version and could not be updated; run /login cliproxyapi for: ',
    cliProxyChangeSeparator: ', ',
    cliProxyChangeProtocols: 'Claude over Anthropic Messages and chat-only models over Chat Completions',
    cliProxyChangeAdaptive: 'adaptive thinking for Claude', cliProxyChangeRetry: 'waiting out account cooldowns',
    cliProxyChangeAffinity: 'one account per session',
    noTargets: 'This profile has no sign-in targets', configured: 'Configured',
    notSet: 'Not set', readOnly: 'Read-only', stored: 'Stored; the next request uses it',
    loginCancelled: 'Sign-in cancelled', unknownTarget: 'Unknown sign-in target',
    // Status-line labels: lowercase and colon-free, each a dim word before its value.
    context: 'ctx', think: 'think', tokensIn: 'in', tokensOut: 'out', cacheHit: 'cache hit', updateLabel: 'update',
    contextCompactsAt: 'compacts at', contextCompactsNext: 'compacts next',
    permission: 'Access', thinking: 'Think', rateUnit: 'tok/s', listCommands: 'List available commands',
    selectModel: 'Choose model and reasoning effort', modelHint: '[provider/model [effort]]', modelSelected: 'Model set for the next turn',
    unknownModel: 'Unknown model', unknownEffort: 'Unknown reasoning effort; this model offers',
    modelBusy: 'Finish or interrupt the turn before changing model',
    thinkingLoading: 'Reasoning efforts are still loading', thinkingUnsupported: 'No reasoning efforts for', thinkingNextStep: 'from the next step',
    noModelSelection: 'This session has no model selection',
    chooseModel: 'Choose model', chooseEffort: 'Choose reasoning effort', providerDefault: 'Provider default',
    currentSelection: 'Current', noChoices: 'No matching choices',
    pickerHelp: '↑↓ choose · Enter selects · Esc cancels', pickerFilter: 'Type to filter', pickerMore: 'more',
    modelsLoading: 'Loading models…', modelCatalogError: 'Unavailable model catalogs',
    modelCancelled: 'Model selection cancelled', modelUsage: 'Usage: /model [provider/model [effort]]',
    completionTitle: 'Commands and skills', completionHelp: '↑↓ choose · Tab completes · Esc closes', send: 'Enter sends',
    moreMatches: 'more, keep typing to narrow', moreLines: 'more lines', earlierCalls: 'earlier calls', attemptDiscarded: 'discarded: the text above was not kept', tabCompletes: 'Tab completes',
    filesTitle: 'Workspace files', file: 'File', directory: 'Directory', noFiles: 'No matching paths',
    filesLoading: 'Finding paths…', filesError: 'File discovery failed', filesUnavailable: 'This profile has no file-reference provider',
    skill: 'Skill', catalogLoading: 'Loading skills…', catalogError: 'Skill discovery failed',
    catalogIncomplete: 'Some skill providers are unavailable', noCompletions: 'No matching commands or skills',
    settingsCommand: 'Change terminal and session settings', settingsUsage: 'Usage: /settings', settingsTitle: 'Settings',
    settingsSaved: 'Settings saved to', settingsStored: 'Settings saved', settingsUnsaved: 'No settings file; changes last until exit',
    settingsNextLaunch: 'Next launch', settingsNewSessions: 'New sessions', settingsByFlag: 'Set by --screen', settingsFailed: 'Settings not saved',
    settingsOn: 'On', settingsOff: 'Off',
    settingsScreen: 'Screen', settingsScreenInline: 'Inline, in terminal scrollback', settingsScreenFullscreen: 'Fullscreen, scrollable transcript',
    settingsLocale: 'Language', settingsFrame: 'Borders', settingsFrameAuto: 'Detect from terminal', settingsFrameRound: 'Rounded', settingsFrameClassic: 'ASCII',
    settingsGoalObjective: 'Goal objective on header', settingsResultLines: 'Tool output lines',
    settingsCompletionLimit: 'Menu rows', settingsDoubleInterrupt: 'Ctrl+C quit window', settingsPermission: 'Default access',
    settingsModel: 'Default model', settingsDefault: 'Default', settingsResultLinesNone: 'None, headline only',
    settingsResetSection: 'Reset this section to defaults', settingsResetConfirm: 'Reset every setting in this section to its default?',
    settingsResetKeep: 'Keep my settings', settingsResetDo: 'Reset to defaults', settingsResetField: 'Reset to default',
    settingsSession: 'Session', settingsTerminal: 'Terminal', settingsAgent: 'Agent', settingsShell: 'Shell',
    settingsWeb: 'Web search', settingsAdvanced: 'Advanced', settingsAdvancedAbout: 'Every plugin setting, by section',
    settingsField: 'setting', settingsFields: 'settings', settingsCustom: 'Enter a value…', settingsInFile: 'Edit in the settings file',
    settingsSecretSet: 'Set', settingsSecretUnset: 'Not set', settingsEmpty: 'Empty',
    settingsNotNumber: 'Not a number', settingsBelowMin: 'At least', settingsAboveMax: 'At most', settingsNotStep: 'In steps of',
    settingsDurationHint: 'e.g. 30s, 2m, 500ms', settingsBytesHint: 'e.g. 64KB, 1MB',
    settingsParallelTools: 'Parallel tool calls', settingsSubagentsActive: 'Subagents running at once',
    settingsSubagentDepth: 'Subagent nesting depth', settingsSubagentDepthOff: 'Off, no subagents',
    settingsSubagentModels: 'Subagents may pick a model', settingsShellTimeout: 'Command timeout',
    settingsShellMaxTimeout: 'Longest timeout a command may ask for', settingsShellOutput: 'Command output kept in memory',
    settingsWebUses: 'Searches per request', settingsWebModel: 'Search model', settingsWebTokens: 'Search answer token limit',
  },
  zh: {
    attachFile: "为下一条提示暂存文件",
    attachUsage: "用法：/attach <原样路径>", attachHint: "<路径>",
    removeAttachment: "移除暂存附件",
    removeAttachmentUsage: "用法：/remove-attachment <显示的编号>", removeAttachmentHint: "<编号>",
    clearAttachments: "丢弃暂存附件",
    clearAttachmentsUsage: "用法：/clear-attachments",
    attachmentStaged: "已暂存", attachmentRemoved: "已移除", attachmentsCleared: "已清除",
    attachmentCountOne: "个附件", attachmentCountMany: "个附件",
    attachmentCountLimit: "已达到暂存附件数量上限",
    attachmentsUnavailable: "此配置没有附件或文件系统服务",
    modelNoImages: "所选模型不支持图像输入",
    attachmentModelChanged: "附件准备期间模型已更改；请重新提交",
    attachmentCommandsUnsupported: "请先发送或清除暂存附件再运行此命令",
    attachmentCancelled: "已取消附件提交；草稿已保留",
    attachmentsBeforeNavigation: "请先发送或清除暂存附件再切换会话",
    attachmentsTitle: "暂存附件",
    attachmentsHelp: "Enter 发送 · /remove-attachment <编号> 移除 · /clear-attachments 清除",
    attachmentsSending: "正在准备附件… Esc 取消",
    working: '处理中', stopping: '正在停止', command: '命令',
    compacting: '压缩历史', compactPreparing: '准备中', compactSummarizing: '生成摘要中',
    compactSaving: '保存中', compactWait: '正在压缩… Enter 排队 · Esc 取消',
    planActive: '规划', planEntryPending: '待进入规划', planExitPending: '待退出规划',
    goalActive: '目标进行中', goalHeld: '目标待继续', goalPaused: '目标已暂停', goalBlocked: '目标受阻',
    goalComplete: '目标已完成', goalRound: '轮次', goalResume: '/goal resume 继续',
    goalTitle: '目标', goalReason: '原因', goalKey: 'Ctrl+O', goalOpen: 'Enter 打开',
    sheetClose: 'Esc 关闭', sheetScroll: '↑↓ 滚动', sheetCycle: 'Tab 下一个', sheetSelect: '↑↓ 选择',
    transcriptScroll: '滚轮/PgUp/PgDn 滚动 · Ctrl+Home 开头 · Ctrl+End 最新',
    transcriptPaused: '历史 · 滚轮/PgUp/PgDn 滚动',
    transcriptLatest: '↓ 最新 · Ctrl+End', transcriptUnseen: '↓ 新输出 · Ctrl+End',
    goalObjective: '目标内容', todoActive: '进行中', todoLeft: '待办',
    activityWords: '烘焙中|揉面中|发酵中|打发中|慢炖中|折叠中|上釉中|醒面中|预热中|过筛中|烘烤中|焦糖化中',
    summaryFailed: '失败', summaryFailures: '项失败',
    phaseThinking: '思考', phaseWriting: '撰写', phaseRunning: '运行',
    pending: '待处理输入', nextStep: '下一步', nextTurn: '下一轮',
    clearPending: '丢弃排队输入', clearPendingUsage: '用法：/clear-pending',
    pendingHelp: '/clear-pending 丢弃排队输入', pendingCleared: '已丢弃排队输入', noPending: '没有排队输入',
    prompt: '问点什么', promptCommands: '/ 命令', promptFiles: '@ 文件',
    composerAbove: '上方', composerBelow: '下方',
    welcomeHelp: '列出可用命令', welcomeChangelog: '查看此版本的更新内容',
    newlineKey: 'Ctrl+J', welcomeNewline: '换行 · Shift+Enter：/terminal-setup',
    changelogCommand: '显示此 Bake 版本的更新内容', changelogUsage: '用法：/changelog',
    changelogUnavailable: '此版本没有可用的更新日志',
    terminalSetupCommand: '让 Shift+Enter 在此终端中换行', terminalSetupUsage: '用法：/terminal-setup',
    terminalSetupTitle: '设置 Shift+Enter', terminalSetupAdds: '添加到', terminalSetupCreates: '新建',
    terminalSetupWrite: '写入', terminalSetupBackupFirst: '先备份原文件', terminalSetupNewFile: '新文件',
    terminalSetupCancel: '取消', terminalSetupUnchanged: '不做更改',
    terminalSetupCancelled: '已取消终端设置；未做更改',
    terminalSetupDone: 'Shift+Enter 现在会换行', terminalSetupWrote: '已更新', terminalSetupCreated: '已创建',
    terminalSetupBackup: '原文件已备份到', terminalSetupUndo: '如需撤销，请运行',
    terminalSetupLive: '会立即应用此更改', terminalSetupTest: '在输入框中按 Shift+Enter 试试',
    terminalSetupRestart: '如果 Shift+Enter 仍然提交，请重启',
    terminalSetupReloadGhostty: '重新加载 Ghostty 配置后生效：Ctrl+Shift+,（macOS 上为 Cmd+Shift+,），或重启 Ghostty',
    terminalSetupReloadKitty: '重新加载 kitty 配置后生效：Ctrl+Shift+F5（macOS 上为 Ctrl+Cmd+,）',
    terminalSetupPresent: 'Shift+Enter 已可换行；未做更改',
    terminalSetupConflict: 'Shift+Enter 已绑定到其他操作；Bake 未做更改',
    terminalSetupReplace: '如需让 Shift+Enter 换行，请将该绑定替换为：',
    terminalSetupUnreadable: 'Bake 无法解析此文件的语法，因此未做任何更改',
    terminalSetupManual: '如需手动设置，请将以下内容添加到', terminalSetupFailed: '无法写入文件',
    terminalSetupNoFile: '其通常位置没有 settings.json',
    terminalSetupTmux: '在 tmux 中：此设置作用于外层终端',
    terminalSetupRemote: 'Bake 运行在另一台机器上；请在你本机的终端中设置：',
    terminalSetupUnknown: 'Bake 无法识别此终端',
    terminalSetupGeneric: '请将其 Shift+Enter 设为发送 ESC CR（\\x1b\\r）；Ctrl+J 和 Alt+Enter 在任何终端中都可换行',
    terminalSetupAlways: 'Ctrl+J 在任何终端中都可换行',
    terminalSetupEditorSteps: '在命令面板中运行 "Preferences: Open Keyboard Shortcuts (JSON)"，并添加：',
    terminalSetupWindowsTerminal: '在 Windows Terminal 中按住 Shift 选择“设置”以打开 settings.json，并将以下内容添加到 "actions"：',
    terminalSetupWezterm: '将以下内容添加到 ~/.wezterm.lua 的 config.keys；WezTerm 保存后会自动重新加载：',
    terminalSetupIterm: 'Settings → Profiles → Keys → Key Mappings → +：按下 Shift+Return，选择 Send Hex Code，并输入 0x1b 0x0d',
    terminalSetupItermOption: '如需 Option+Enter 也换行：Settings → Profiles → Keys → General → Left Option key 设为 Esc+',
    terminalSetupApple: '终端会将 Shift+Enter 作为普通 Enter 发送。打开“设置 → 描述文件 → 键盘 → 将 Option 键用作 Meta 键”后，'
      + 'Option+Enter 即可换行',
    terminalSetupAlacrittyYaml: '这是旧版 alacritty.yml，Bake 不会编辑它；请运行 alacritty migrate 后再次运行 /terminal-setup，'
      + '或将以下内容添加到 key_bindings 中，文件位于',
    terminalSetupAlacrittyInline: '此文件将按键绑定写在一个内联数组中，Bake 不会编辑它',
    updateCommand: '安装最新的 Bake 版本', updateUsage: '用法：/update',
    updateChecking: '正在检查 Bake 新版本…', updateDownloading: '正在下载 Bake', updateUnpacking: '正在解压 Bake',
    updateVerifying: '正在检查新版本能否启动', updateCurrent: 'Bake 已是最新版本',
    updateUnavailable: '新版 Bake 已发布，但尚未提供此平台的版本',
    updateUnsupported: 'Bake 未发布此平台的版本',
    updateUnmanaged: '此 Bake 不受更新程序管理',
    updateUnmanagedHint: '源码检出请运行 git pull && bun install --frozen-lockfile && bun run build；其他副本请重新安装',
    updateInstalled: 'Bake 已更新；新会话将使用新版本，当前会话继续运行', updateRestart: '重启后生效',
    updateFailed: '更新失败', updateCancelled: '已取消更新；安装未改变',
    preview: '预览', previewReplaying: '回放中', previewPrompt: '试试输入框', previewSend: 'Enter 预览',
    previewHelp: '组件预览 · 未连接智能体\n真实对话：bun run dev:tui',
    previewAccepted: '已显示预览消息；未连接智能体。',
    interrupt: 'Esc 中断',
    editHelp: '←→ 移动 · Home/End 行首行尾 · ↑↓ 逐行，再到历史 · Ctrl+J 或 Alt+Enter 换行 · Shift+Enter：/terminal-setup',
    steering: 'Enter 将输入发送到下一步', quit: '再次按 Ctrl-C 退出',
    approval: '需要批准', approve: 'Y 允许一次 · N 拒绝',
    questions: '等待回答', customAnswer: '其他回答', customAnswerHint: '输入你自己的回答',
    questionSelected: '项已选', questionChooseOne: '请至少勾选一项，或输入你自己的回答',
    questionTypeFirst: '请先输入回答，或选择一个选项',
    questionPickerHelp: '↑↓ 选择 · 1-9 跳转 · Enter 确认 · 直接输入回答 · Esc 取消',
    multiPickerHelp: '↑↓ 选择 · Space 勾选 · Enter 提交 · 直接输入回答 · Esc 取消',
    cancelled: '已中断', compacted: '上下文已压缩',
    turn: '回合', turnCompleted: '已完成', turnBlocked: '受阻', turnMaxTokens: '已达到输出 token 上限',
    cardLine: '行', cardLines: '行', cardMatch: '处匹配', cardMatches: '处匹配',
    cardPath: '个路径', cardPaths: '个路径', cardSource: '个来源', cardSources: '个来源',
    cardTruncated: '已截断',
    todoTitle: '任务', todoDone: '已完成', todoKey: 'Ctrl+T', todoOpen: 'Enter 打开',
    unknownCommand: '未知命令', commandBusy: '已有命令正在运行',
    didYouMean: '是否要输入', unknownCommandHint: '以空格开头可作为消息发送',
    usage: '用法', helpHint: '[命令]', helpFooter: '输入 / 浏览 · /help <命令> 查看单个命令 · Tab 补全',
    aliasOf: '等同于',
    chooseSession: '选择会话', newSession: '新建会话', untitledSession: '未命名会话', resumeSession: '浏览会话或新建会话',
    ageNow: '刚刚', ageMinutes: '分钟前', ageHours: '小时前', ageDays: '天前',
    newSessionCommand: '新建会话；当前会话会保留',
    sessionsLoading: '正在加载会话…', sessionOpening: '正在打开会话…',
    sessionsIdle: '请先完成或中断当前回合再切换会话',
    sessionsPending: '请先处理或清除排队输入再切换会话',
    sessionsBusy: '正在切换会话', sessionsCancelled: '已取消会话导航',
    sessionsError: '会话导航失败', sessionTitlesUnavailable: '部分会话标题不可用；请按 ID 选择',
    sessionInUse: '此会话已在另一个 Bake 进程中打开；请先在那里关闭它再在此继续，或使用 /new 新建会话',
    sessionInUseLaunch: '已在另一个 Bake 进程中打开；请先在那里关闭它再重新运行此命令，或去掉 --resume 以新建会话',
    sessionNeedsPreset: '此会话未记录预设；请改用命令行的 --resume 和 --preset 恢复它',
    session: '会话', cancelHelp: 'Esc 取消',
    noCredentials: '尚未配置凭据；输入 /login 设置',
    signIn: '登录提供方或配置 CLIProxyAPI', loginHint: '[目标]', pasteCredential: '粘贴凭据值',
    listSubagents: '列出委派代理', agentsUsage: '用法：/agents [ID]',
    subagentsTitle: '子代理', subagentsOpen: 'Enter 打开', subagentsKey: 'Ctrl+G', noSubagents: '此会话没有子代理',
    subagentsUnavailable: '此配置没有子代理服务',
    subagentCompleted: '已完成', subagentFailed: '失败', subagentStopped: '已停止',
    subagentWorking: '工作中', subagentLive: '在线', subagentSaved: '已保存', subagentOneShot: '单次',
    subagentContinuable: '可继续', subagentIssue: '无法读取的子代理', subagentUnreadable: '无法读取',
    subagentCountWorking: '工作中',
    subagentRemote: '远程任务', subagentNoTranscript: '没有可用的本地记录',
    subagentChoose: '选择子代理查看会话，父代理会继续运行。',
    subagentBack: '只读 · Esc 返回父会话', subagentParent: '父会话',
    chooseLogin: '选择登录目标', cliProxySetupHint: '地址 + API 密钥',
    cliProxyReady: '个模型已就绪；使用 /model 选择', cliProxyReadyOne: '个模型已就绪；使用 /model 选择',
    loginHelp: 'Enter 继续 · Esc 取消',
    cliProxyUrl: 'CLIProxyAPI 服务器地址', cliProxyKey: 'CLIProxyAPI API 密钥',
    cliProxyChecking: '正在检查 CLIProxyAPI 模型…',
    cliProxyUpgraded: '已为此版本更新 CLIProxyAPI 路由：',
    cliProxyRelogin: 'CLIProxyAPI 路由来自旧版本且无法自动更新；请运行 /login cliproxyapi 以启用：',
    cliProxyChangeSeparator: '、',
    cliProxyChangeProtocols: 'Claude 走 Anthropic Messages、仅支持聊天的模型走 Chat Completions',
    cliProxyChangeAdaptive: 'Claude 自适应思考', cliProxyChangeRetry: '等待账号冷却结束',
    cliProxyChangeAffinity: '每个会话固定一个账号',
    noTargets: '此配置没有登录目标', configured: '已配置',
    notSet: '未设置', readOnly: '只读', stored: '已保存；下次请求将使用它',
    loginCancelled: '已取消登录', unknownTarget: '未知登录目标',
    context: '上下文', think: '思考', tokensIn: '输入', tokensOut: '输出', cacheHit: '缓存命中', updateLabel: '可更新',
    contextCompactsAt: '压缩于', contextCompactsNext: '即将压缩',
    permission: '权限', thinking: '思考', rateUnit: 'token/秒', listCommands: '列出可用命令',
    selectModel: '选择模型和推理强度', modelHint: '[provider/model [effort]]', modelSelected: '模型已设置，下一轮生效',
    unknownModel: '未知模型', unknownEffort: '未知推理强度；此模型支持',
    modelBusy: '请先完成或中断当前回合再切换模型',
    thinkingLoading: '推理强度仍在加载', thinkingUnsupported: '该模型不支持推理强度', thinkingNextStep: '从下一步生效',
    noModelSelection: '此会话没有模型选择',
    chooseModel: '选择模型', chooseEffort: '选择推理强度', providerDefault: '提供器默认值',
    currentSelection: '当前', noChoices: '没有匹配的选项',
    pickerHelp: '↑↓ 选择 · Enter 确认 · Esc 取消', pickerFilter: '输入以筛选', pickerMore: '项未显示',
    modelsLoading: '正在加载模型…', modelCatalogError: '无法读取以下模型目录',
    modelCancelled: '已取消模型选择', modelUsage: '用法：/model [provider/model [effort]]',
    completionTitle: '命令和技能', completionHelp: '↑↓ 选择 · Tab 补全 · Esc 关闭', send: 'Enter 发送',
    moreMatches: '个更多，继续输入以缩小范围', moreLines: '行未显示', earlierCalls: '个较早的调用', attemptDiscarded: '已丢弃：上方文字未保存', tabCompletes: 'Tab 补全',
    filesTitle: '工作区文件', file: '文件', directory: '目录', noFiles: '没有匹配的路径',
    filesLoading: '正在查找路径…', filesError: '文件发现失败', filesUnavailable: '此配置没有文件引用提供器',
    skill: '技能', catalogLoading: '正在加载技能…', catalogError: '技能发现失败',
    catalogIncomplete: '部分技能提供器不可用', noCompletions: '没有匹配的命令或技能',
    settingsCommand: '更改终端和会话设置', settingsUsage: '用法：/settings', settingsTitle: '设置',
    settingsSaved: '设置已保存到', settingsStored: '设置已保存', settingsUnsaved: '没有设置文件；更改仅在本次运行有效',
    settingsNextLaunch: '下次启动生效', settingsNewSessions: '新会话生效', settingsByFlag: '由 --screen 指定', settingsFailed: '设置未保存',
    settingsOn: '开', settingsOff: '关',
    settingsScreen: '屏幕', settingsScreenInline: '内联，使用终端回滚', settingsScreenFullscreen: '全屏，可滚动的对话记录',
    settingsLocale: '语言', settingsFrame: '边框', settingsFrameAuto: '根据终端检测', settingsFrameRound: '圆角', settingsFrameClassic: 'ASCII',
    settingsGoalObjective: '标题行显示目标内容', settingsResultLines: '工具输出行数',
    settingsCompletionLimit: '菜单行数', settingsDoubleInterrupt: 'Ctrl+C 退出确认时长', settingsPermission: '默认权限',
    settingsModel: '默认模型', settingsDefault: '默认', settingsResultLinesNone: '不显示，仅标题',
    settingsResetSection: '将本节恢复为默认值', settingsResetConfirm: '将本节所有设置恢复为默认值？',
    settingsResetKeep: '保留当前设置', settingsResetDo: '恢复默认值', settingsResetField: '恢复默认值',
    settingsSession: '会话', settingsTerminal: '终端', settingsAgent: '代理', settingsShell: 'Shell',
    settingsWeb: '网页搜索', settingsAdvanced: '高级', settingsAdvancedAbout: '按分区列出所有插件设置',
    settingsField: '项设置', settingsFields: '项设置', settingsCustom: '输入值…', settingsInFile: '请在设置文件中编辑',
    settingsSecretSet: '已设置', settingsSecretUnset: '未设置', settingsEmpty: '空',
    settingsNotNumber: '不是数字', settingsBelowMin: '最小为', settingsAboveMax: '最大为', settingsNotStep: '步长为',
    settingsDurationHint: '例如 30s、2m、500ms', settingsBytesHint: '例如 64KB、1MB',
    settingsParallelTools: '并行工具调用数', settingsSubagentsActive: '同时运行的子代理数',
    settingsSubagentDepth: '子代理嵌套深度', settingsSubagentDepthOff: '关闭，不使用子代理',
    settingsSubagentModels: '子代理可选择模型', settingsShellTimeout: '命令超时',
    settingsShellMaxTimeout: '命令可请求的最长超时', settingsShellOutput: '内存中保留的命令输出',
    settingsWebUses: '每次请求的搜索次数', settingsWebModel: '搜索模型', settingsWebTokens: '搜索回答令牌上限',
  },
} as const

/** Supported terminal locales. */
export type Locale = keyof typeof dictionaries
/** Labels supplied to presentation components by the application. */
export type TuiCopy = { readonly [K in keyof typeof dictionaries.en]: string }
